\lemma grequation0{G : Group}(x0 x1 x2 x3 x4 : G): x1 = x1 => equation.group

\lemma grequation1{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((((x5 G.* (G.inverse x5)) G.* x4) G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x4))) G.* ((x5 G.* (x0 G.* (G.inverse x0))) G.* ((G.inverse x5) G.* x5))) = x5 => equation.group

\lemma grequation2{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation3{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x6 G.* x7) G.* x6) G.* ((G.inverse x6) G.* ((((G.inverse x7) G.* ((G.inverse x6) G.* x5)) G.* (G.inverse x5)) G.* (x5 G.* (x4 G.* x2))))) = (x5 G.* (x4 G.* x2)) => equation.group

\lemma grequation4{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = ((x5 G.* (x4 G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x4)))) G.* (((G.inverse x5) G.* (x2 G.* (G.inverse x2))) G.* ((x1 G.* (G.inverse x1)) G.* (x4 G.* (G.inverse x4))))) => equation.group

\lemma grequation5{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation6{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x4 G.* ((x5 G.* (x3 G.* (x7 G.* (G.inverse x7)))) G.* (G.inverse x3))) = (x4 G.* x5) => equation.group

\lemma grequation7{G : Group}(x0 x1 x2 x3 x4 : G): (((((x0 G.* x4) G.* x0) G.* ((G.inverse x0) G.* (x3 G.* (x4 G.* x2)))) G.* (((G.inverse x2) G.* x0) G.* (G.inverse x0))) G.* ((x4 G.* ((G.inverse x4) G.* (G.inverse x4))) G.* (G.inverse x3))) = (x0 G.* x4) => equation.group

\lemma grequation8{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x4 = ((x4 G.* (x2 G.* x4)) G.* (((((x0 G.* (G.inverse x0)) G.* (G.inverse x4)) G.* x7) G.* (G.inverse x7)) G.* (G.inverse x2))) => equation.group

\lemma grequation9{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x8 G.* (G.inverse x8)) = ((x7 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x7))) => equation.group

\lemma grequation10{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation11{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x3 G.* (((G.inverse x3) G.* (x5 G.* x5)) G.* (G.inverse x5))) = x5 => equation.group

\lemma grequation12{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x2 G.* ((G.inverse x2) G.* x0)) = ((x2 G.* (G.inverse x2)) G.* (x0 G.* (x11 G.* (G.inverse x11)))) => equation.group

\lemma grequation13{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = (x4 G.* ((G.inverse x4) G.* x0)) => equation.group

\lemma grequation14{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x3 G.* ((G.inverse x3) G.* (x7 G.* (G.inverse x7)))) => equation.group

\lemma grequation15{G : Group}(x0 x1 x2 x3 : G): x1 = x1 => equation.group

\lemma grequation16{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation17{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x2 G.* (G.inverse x2)) = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation18{G : Group}(x0 x1 x2 x3 x4 : G): (x1 G.* x4) = (x1 G.* x4) => equation.group

\lemma grequation19{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* x4) = (x3 G.* x4) => equation.group

\lemma grequation20{G : Group}(x0 x1 x2 : G): ((x2 G.* (G.inverse x2)) G.* (x1 G.* x2)) = (x1 G.* ((x2 G.* x0) G.* (G.inverse x0))) => equation.group

\lemma grequation21{G : Group}(x0 x1 x2 x3 x4 : G): ((((x0 G.* x4) G.* (x2 G.* (x2 G.* x0))) G.* ((x4 G.* (G.inverse x4)) G.* (x4 G.* ((G.inverse x4) G.* (G.inverse x0))))) G.* ((G.inverse x2) G.* ((G.inverse x2) G.* (G.inverse x4)))) = x0 => equation.group

\lemma grequation22{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x0 G.* (((G.inverse x0) G.* x5) G.* x1)) = (((((x6 G.* (G.inverse x6)) G.* x5) G.* ((x7 G.* (G.inverse x7)) G.* ((G.inverse x5) G.* x5))) G.* (x0 G.* (((G.inverse x0) G.* x1) G.* x3))) G.* (G.inverse x3)) => equation.group

\lemma grequation23{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x4 G.* (G.inverse x4)) G.* (x1 G.* (G.inverse x1))) = ((((x0 G.* (x2 G.* (G.inverse x2))) G.* (G.inverse x0)) G.* x4) G.* ((G.inverse x4) G.* (x5 G.* (G.inverse x5)))) => equation.group

\lemma grequation24{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x4 G.* x10) = (x4 G.* x10) => equation.group

\lemma grequation25{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x8 G.* x8) G.* ((G.inverse x8) G.* (x5 G.* x1))) G.* (G.inverse x1)) = (x8 G.* x5) => equation.group

\lemma grequation26{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x3 G.* (G.inverse x3)) G.* x7) = ((((x0 G.* x12) G.* (x3 G.* x6)) G.* (((G.inverse x6) G.* (G.inverse x3)) G.* (G.inverse x12))) G.* ((G.inverse x0) G.* x7)) => equation.group

\lemma grequation27{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x1 G.* x1) G.* (x5 G.* (G.inverse x5))) = ((x6 G.* (x8 G.* (G.inverse x8))) G.* (((G.inverse x6) G.* x1) G.* x1)) => equation.group

\lemma grequation28{G : Group}(x0 x1 x2 x3 : G): ((x1 G.* ((G.inverse x1) G.* x3)) G.* x2) = (x3 G.* x2) => equation.group

\lemma grequation29{G : Group}(x0 x1 x2 x3 x4 : G): ((x2 G.* (x0 G.* (((G.inverse x0) G.* x2) G.* (G.inverse x2)))) G.* x4) = (x2 G.* x4) => equation.group

\lemma grequation30{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x2 G.* ((x3 G.* x7) G.* (((x5 G.* (G.inverse x5)) G.* (G.inverse x7)) G.* (x9 G.* x0)))) G.* ((G.inverse x0) G.* (G.inverse x9))) = ((x13 G.* (G.inverse x13)) G.* (((x3 G.* (G.inverse x3)) G.* x2) G.* x3)) => equation.group

\lemma grequation31{G : Group}(x0 x1 x2 : G): (x1 G.* ((G.inverse x1) G.* x0)) = x0 => equation.group

\lemma grequation32{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x3 = (((((x5 G.* (G.inverse x5)) G.* x14) G.* (x5 G.* (x11 G.* (G.inverse x11)))) G.* (G.inverse x5)) G.* ((G.inverse x14) G.* x3)) => equation.group

\lemma grequation33{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x3 G.* (G.inverse x3)) G.* x9) = ((x3 G.* (G.inverse x3)) G.* x9) => equation.group

\lemma grequation34{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x7 = x7 => equation.group

\lemma grequation35{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x12 G.* ((G.inverse x12) G.* x4)) G.* ((G.inverse x4) G.* (x10 G.* (x3 G.* x7)))) = ((x10 G.* x3) G.* x7) => equation.group

\lemma grequation36{G : Group}(x0 x1 x2 x3 x4 : G): x1 = ((x1 G.* (x1 G.* (x1 G.* (G.inverse x1)))) G.* (G.inverse x1)) => equation.group

\lemma grequation37{G : Group}(x0 x1 x2 : G): ((x0 G.* x0) G.* (G.inverse x0)) = (x2 G.* ((G.inverse x2) G.* x0)) => equation.group

\lemma grequation38{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x3 G.* (x5 G.* ((G.inverse x5) G.* ((G.inverse x3) G.* ((x3 G.* (G.inverse x3)) G.* (x3 G.* (G.inverse x3))))))) => equation.group

\lemma grequation39{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x8 G.* (G.inverse x8)) G.* x0) = (x3 G.* ((G.inverse x3) G.* x0)) => equation.group

\lemma grequation40{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x12 G.* (G.inverse x12)) => equation.group

\lemma grequation41{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x8 G.* x3) G.* (((x5 G.* x8) G.* (((G.inverse x8) G.* x1) G.* (G.inverse x1))) G.* (G.inverse x5))) = (((x8 G.* x3) G.* (x4 G.* x8)) G.* (((x1 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x1) G.* ((G.inverse x8) G.* (G.inverse x4))))) => equation.group

\lemma grequation42{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x12 G.* ((((x5 G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x5))) G.* (x8 G.* (G.inverse x8))) G.* (G.inverse x12)) G.* (x4 G.* x10))) = (x4 G.* x10) => equation.group

\lemma grequation43{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (((((x1 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x1)) G.* x4) G.* ((x3 G.* (G.inverse x3)) G.* (G.inverse x4))) => equation.group

\lemma grequation44{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x9 G.* x7) = (x9 G.* x7) => equation.group

\lemma grequation45{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x11 G.* (x10 G.* ((G.inverse x10) G.* (G.inverse x11)))) G.* (x11 G.* (((((G.inverse x11) G.* x9) G.* ((G.inverse x9) G.* x1)) G.* (((x14 G.* x13) G.* (G.inverse x13)) G.* (G.inverse x14))) G.* x13))) = (x1 G.* ((x13 G.* x14) G.* (G.inverse x14))) => equation.group

\lemma grequation46{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation47{G : Group}(x0 x1 x2 : G): ((x0 G.* x1) G.* x2) = (x0 G.* (x1 G.* x2)) => equation.group

\lemma grequation48{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x10 G.* (G.inverse x10)) => equation.group

\lemma grequation49{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x1 G.* x10) G.* (x3 G.* (x10 G.* (G.inverse x10)))) = (((x1 G.* x10) G.* (x3 G.* x0)) G.* ((G.inverse x0) G.* (x1 G.* (G.inverse x1)))) => equation.group

\lemma grequation50{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = ((x9 G.* ((((x12 G.* x8) G.* (x11 G.* (x5 G.* x5))) G.* (G.inverse x5)) G.* (G.inverse x5))) G.* ((((G.inverse x11) G.* (G.inverse x8)) G.* x6) G.* (((G.inverse x6) G.* (G.inverse x12)) G.* (G.inverse x9)))) => equation.group

\lemma grequation51{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x5 G.* (G.inverse x5)) = ((x0 G.* x9) G.* ((G.inverse x9) G.* (G.inverse x0))) => equation.group

\lemma grequation52{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation53{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x7 = x7 => equation.group

\lemma grequation54{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((((x11 G.* (x8 G.* (G.inverse x8))) G.* x13) G.* x3) G.* x7) = ((x11 G.* x13) G.* ((x3 G.* x7) G.* (x8 G.* (G.inverse x8)))) => equation.group

\lemma grequation55{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x7 G.* ((G.inverse x7) G.* x2)) G.* x6) = (x2 G.* ((x10 G.* (x8 G.* (G.inverse x8))) G.* ((G.inverse x10) G.* x6))) => equation.group

\lemma grequation56{G : Group}(x0 x1 : G): x1 = (x1 G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation57{G : Group}(x0 x1 : G): (x0 G.* ((G.inverse x0) G.* ((x0 G.* (G.inverse x0)) G.* (x1 G.* x0)))) = (x1 G.* x0) => equation.group

\lemma grequation58{G : Group}(x0 x1 x2 : G): (x1 G.* x1) = (x1 G.* x1) => equation.group

\lemma grequation59{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x1 G.* (G.inverse x1)) G.* x0) = x0 => equation.group

\lemma grequation60{G : Group}(x0 x1 : G): (x1 G.* (x0 G.* x0)) = (x1 G.* (x0 G.* x0)) => equation.group

\lemma grequation61{G : Group}(x0 x1 x2 x3 : G): (x2 G.* (x1 G.* (G.inverse x1))) = (((x0 G.* (G.inverse x0)) G.* ((((x3 G.* x3) G.* (x0 G.* x3)) G.* (G.inverse x3)) G.* (((G.inverse x0) G.* (G.inverse x3)) G.* (G.inverse x3)))) G.* x2) => equation.group

\lemma grequation62{G : Group}(x0 x1 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation63{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation64{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* (G.inverse x0)) G.* (x2 G.* x3)) = ((((x2 G.* x3) G.* (x2 G.* x3)) G.* (x1 G.* (G.inverse x1))) G.* ((G.inverse x3) G.* (G.inverse x2))) => equation.group

\lemma grequation65{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation66{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x8 G.* (((G.inverse x8) G.* x2) G.* (G.inverse x2))) => equation.group

\lemma grequation67{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation68{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x4 G.* (x6 G.* (((x7 G.* (G.inverse x7)) G.* (G.inverse x6)) G.* (G.inverse x4)))) => equation.group

\lemma grequation69{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (((x8 G.* (G.inverse x8)) G.* x3) G.* (x8 G.* (G.inverse x8))) = x3 => equation.group

\lemma grequation70{G : Group}(x0 x1 : G): x1 = (x0 G.* ((G.inverse x0) G.* x1)) => equation.group

\lemma grequation71{G : Group}(x0 x1 x2 x3 x4 x5 : G): x0 = x0 => equation.group

\lemma grequation72{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x8 G.* (G.inverse x8)) = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation73{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x0 G.* x4) = (((x0 G.* x4) G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation74{G : Group}(x0 x1 x2 x3 x4 : G): ((x3 G.* (G.inverse x3)) G.* (x3 G.* (G.inverse x3))) = (((x3 G.* ((x1 G.* (x0 G.* (G.inverse x0))) G.* x4)) G.* ((G.inverse x4) G.* (G.inverse x1))) G.* ((G.inverse x3) G.* (x1 G.* (G.inverse x1)))) => equation.group

\lemma grequation75{G : Group}(x0 x1 x2 x3 : G): (x2 G.* (G.inverse x2)) = (((x1 G.* (G.inverse x1)) G.* x3) G.* (G.inverse x3)) => equation.group

\lemma grequation76{G : Group}(x0 x1 x2 : G): x0 = (x0 G.* ((G.inverse x0) G.* x0)) => equation.group

\lemma grequation77{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x8 = (x3 G.* (x0 G.* ((G.inverse x0) G.* ((G.inverse x3) G.* x8)))) => equation.group

\lemma grequation78{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x6 G.* ((G.inverse x6) G.* x4)) G.* (G.inverse x4)) = (x2 G.* (x6 G.* ((G.inverse x6) G.* ((x8 G.* (G.inverse x8)) G.* (G.inverse x2))))) => equation.group

\lemma grequation79{G : Group}(x0 x1 x2 x3 x4 : G): x2 = x2 => equation.group

\lemma grequation80{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x7 G.* (G.inverse x7)) G.* x0) = x0 => equation.group

\lemma grequation81{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x7 G.* ((((G.inverse x7) G.* x8) G.* x2) G.* (G.inverse x2))) G.* (((G.inverse x8) G.* x3) G.* (x6 G.* (G.inverse x6)))) = x3 => equation.group

\lemma grequation82{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((x10 G.* ((G.inverse x10) G.* x8)) G.* (G.inverse x8)) G.* (x9 G.* x14)) = (x9 G.* x14) => equation.group

\lemma grequation83{G : Group}(x0 x1 : G): G.ide = ((x1 G.* (((G.inverse x1) G.* (x1 G.* (G.inverse x1))) G.* (x1 G.* (G.inverse x1)))) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation84{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x2 G.* ((G.inverse x2) G.* x1)) G.* (G.inverse x1)) G.* x0) = (x0 G.* (x5 G.* (((x2 G.* x5) G.* ((G.inverse x5) G.* (G.inverse x2))) G.* (G.inverse x5)))) => equation.group

\lemma grequation85{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation86{G : Group}(x0 x1 : G): ((x1 G.* (G.inverse x1)) G.* ((x0 G.* x1) G.* ((G.inverse x1) G.* x1))) = (((((x1 G.* x0) G.* x0) G.* (G.inverse x0)) G.* (G.inverse x0)) G.* ((((G.inverse x1) G.* x0) G.* (x1 G.* x1)) G.* (G.inverse x1))) => equation.group

\lemma grequation87{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x4 = x4 => equation.group

\lemma grequation88{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x4 = (x4 G.* ((x0 G.* (G.inverse x0)) G.* (x7 G.* (G.inverse x7)))) => equation.group

\lemma grequation89{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = ((x5 G.* x3) G.* (((x6 G.* (x5 G.* (G.inverse x5))) G.* ((G.inverse x6) G.* (G.inverse x3))) G.* (G.inverse x5))) => equation.group

\lemma grequation90{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x3 G.* ((G.inverse x3) G.* x3)) G.* (G.inverse x3)) => equation.group

\lemma grequation91{G : Group}(x0 x1 x2 : G): x2 = x2 => equation.group

\lemma grequation92{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x9 G.* x6) = ((x0 G.* ((G.inverse x0) G.* x9)) G.* x6) => equation.group

\lemma grequation93{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x4 G.* (G.inverse x4)) G.* x6) = (((x6 G.* (x0 G.* x2)) G.* (G.inverse x2)) G.* (G.inverse x0)) => equation.group

\lemma grequation94{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x1 G.* (((G.inverse x1) G.* x5) G.* (G.inverse x5))) G.* x6) = x6 => equation.group

\lemma grequation95{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x7 = ((((x7 G.* x0) G.* x2) G.* (x7 G.* (G.inverse x7))) G.* ((G.inverse x2) G.* ((x11 G.* x0) G.* (((G.inverse x0) G.* (G.inverse x11)) G.* (G.inverse x0))))) => equation.group

\lemma grequation96{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x6 G.* x1) G.* (G.inverse x1)) = x6 => equation.group

\lemma grequation97{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x4 G.* (((G.inverse x4) G.* x4) G.* (G.inverse x4))) => equation.group

\lemma grequation98{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x10 G.* ((G.inverse x10) G.* x2)) G.* (x8 G.* ((G.inverse x8) G.* x10))) = (x2 G.* x10) => equation.group

\lemma grequation99{G : Group}(x0 x1 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation100{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x5 = (x3 G.* (((G.inverse x3) G.* x7) G.* ((G.inverse x7) G.* x5))) => equation.group

\lemma grequation101{G : Group}(x0 x1 : G): x1 = ((((x1 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x1)) G.* (x1 G.* (x1 G.* (G.inverse x1)))) => equation.group

\lemma grequation102{G : Group}(x0 x1 x2 x3 x4 x5 : G): (((((x0 G.* (G.inverse x0)) G.* (x2 G.* (x2 G.* (x1 G.* ((G.inverse x1) G.* x2))))) G.* ((G.inverse x2) G.* x4)) G.* x3) G.* (G.inverse x3)) = ((x2 G.* x2) G.* x4) => equation.group

\lemma grequation103{G : Group}(x0 x1 x2 x3 x4 : G): x2 = ((x2 G.* x2) G.* (G.inverse x2)) => equation.group

\lemma grequation104{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x6 G.* x2) G.* (G.inverse x2)) = x6 => equation.group

\lemma grequation105{G : Group}(x0 x1 : G): (x1 G.* ((x1 G.* x1) G.* (G.inverse x1))) = (x1 G.* x1) => equation.group

\lemma grequation106{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x2 G.* (G.inverse x2)) = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation107{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x5 = x5 => equation.group

\lemma grequation108{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x8 G.* ((G.inverse x8) G.* x1)) G.* (G.inverse x1)) G.* (x4 G.* x0)) = (x4 G.* (((G.inverse x4) G.* (x4 G.* x0)) G.* (x3 G.* (G.inverse x3)))) => equation.group

\lemma grequation109{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x2 G.* (G.inverse x2)) G.* x1) = (x3 G.* ((G.inverse x3) G.* x1)) => equation.group

\lemma grequation110{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x0 = x0 => equation.group

\lemma grequation111{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x2 G.* (G.inverse x2)) G.* x2) G.* ((x2 G.* (G.inverse x2)) G.* ((x10 G.* (x7 G.* (G.inverse x7))) G.* (G.inverse x10)))) = x2 => equation.group

\lemma grequation112{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x6 G.* (G.inverse x6)) G.* x6) = x6 => equation.group

\lemma grequation113{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x2 G.* ((x5 G.* (G.inverse x5)) G.* x2)) = (x2 G.* x2) => equation.group

\lemma grequation114{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x5 G.* ((x3 G.* (x10 G.* (G.inverse x10))) G.* (G.inverse x3))) = x5 => equation.group

\lemma grequation115{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x4 G.* (G.inverse x4)) G.* ((((x2 G.* (G.inverse x2)) G.* (x0 G.* ((G.inverse x0) G.* (x4 G.* x1)))) G.* (G.inverse x1)) G.* (((x2 G.* (G.inverse x2)) G.* (((G.inverse x4) G.* x0) G.* x11)) G.* x9))) G.* (G.inverse x9)) = ((x0 G.* x7) G.* ((G.inverse x7) G.* x11)) => equation.group

\lemma grequation116{G : Group}(x0 x1 x2 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation117{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x6 G.* ((G.inverse x6) G.* x10)) = ((x10 G.* x10) G.* ((x4 G.* (((G.inverse x4) G.* x9) G.* (G.inverse x9))) G.* (((G.inverse x10) G.* x13) G.* (G.inverse x13)))) => equation.group

\lemma grequation118{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x2 G.* (G.inverse x2)) G.* (x9 G.* (G.inverse x9))) G.* ((x8 G.* (x8 G.* (G.inverse x8))) G.* ((G.inverse x8) G.* x7))) = ((x7 G.* x3) G.* (((G.inverse x3) G.* (G.inverse x7)) G.* x7)) => equation.group

\lemma grequation119{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x0 = x0 => equation.group

\lemma grequation120{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x11 G.* (G.inverse x11)) G.* x6) G.* ((G.inverse x6) G.* (x4 G.* (G.inverse x4)))) = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation121{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((((x9 G.* (G.inverse x9)) G.* (x6 G.* (G.inverse x6))) G.* ((x8 G.* ((G.inverse x8) G.* x4)) G.* (x2 G.* ((G.inverse x2) G.* x3)))) G.* ((((x8 G.* ((G.inverse x8) G.* x7)) G.* (((G.inverse x7) G.* x9) G.* (G.inverse x9))) G.* (G.inverse x3)) G.* (G.inverse x4))) = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation122{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x4 G.* x4) G.* (G.inverse x4)) = ((x4 G.* x9) G.* (G.inverse x9)) => equation.group

\lemma grequation123{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x5 G.* x12) = (((((x5 G.* (G.inverse x5)) G.* (x9 G.* x14)) G.* x0) G.* ((G.inverse x0) G.* x10)) G.* ((((G.inverse x10) G.* (G.inverse x14)) G.* (G.inverse x9)) G.* (x5 G.* x12))) => equation.group

\lemma grequation124{G : Group}(x0 x1 : G): x1 = ((x1 G.* x0) G.* (G.inverse x0)) => equation.group

\lemma grequation125{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x9 G.* (x4 G.* (x6 G.* (G.inverse x6)))) = (((x14 G.* x4) G.* (G.inverse x4)) G.* (((G.inverse x14) G.* x9) G.* x4)) => equation.group

\lemma grequation126{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x8 G.* (x6 G.* ((G.inverse x6) G.* (G.inverse x8)))) = ((x9 G.* (((G.inverse x9) G.* x6) G.* x9)) G.* (x4 G.* (((G.inverse x4) G.* (G.inverse x9)) G.* (G.inverse x6)))) => equation.group

\lemma grequation127{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x1 = (x1 G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation128{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x8 G.* (x12 G.* x8)) = (x8 G.* (((x12 G.* x8) G.* x4) G.* (G.inverse x4))) => equation.group

\lemma grequation129{G : Group}(x0 x1 x2 x3 x4 : G): ((((x3 G.* (G.inverse x3)) G.* x2) G.* ((G.inverse x2) G.* x4)) G.* (((G.inverse x4) G.* x2) G.* ((G.inverse x2) G.* (x3 G.* x0)))) = ((x1 G.* (G.inverse x1)) G.* ((x3 G.* (x3 G.* x4)) G.* ((((G.inverse x4) G.* ((G.inverse x3) G.* x3)) G.* (G.inverse x3)) G.* x0))) => equation.group

\lemma grequation130{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x6 G.* x7) G.* (G.inverse x7)) G.* (((G.inverse x6) G.* x4) G.* (x0 G.* x5))) = ((((x4 G.* (x0 G.* x1)) G.* x0) G.* ((G.inverse x0) G.* (x4 G.* (G.inverse x4)))) G.* ((G.inverse x1) G.* x5)) => equation.group

\lemma grequation131{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation132{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x4 G.* x10) = (x4 G.* x10) => equation.group

\lemma grequation133{G : Group}(x0 x1 x2 x3 x4 : G): x0 = x0 => equation.group

\lemma grequation134{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = x0 => equation.group

\lemma grequation135{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x10 = x10 => equation.group

\lemma grequation136{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x3 G.* x12) G.* (G.inverse x12)) = x3 => equation.group

\lemma grequation137{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = ((x3 G.* x2) G.* ((G.inverse x2) G.* (G.inverse x3))) => equation.group

\lemma grequation138{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x5 G.* x7) G.* (x4 G.* (G.inverse x4))) = (x5 G.* x7) => equation.group

\lemma grequation139{G : Group}(x0 x1 x2 x3 x4 x5 : G): (((x2 G.* x4) G.* x4) G.* (G.inverse x4)) = ((x2 G.* (x4 G.* x4)) G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x4)))) => equation.group

\lemma grequation140{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x1))) => equation.group

\lemma grequation141{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x0 G.* (G.inverse x0)) G.* (x2 G.* x4)) G.* (G.inverse x4)) = x2 => equation.group

\lemma grequation142{G : Group}(x0 x1 x2 : G): ((x0 G.* (G.inverse x0)) G.* x2) = x2 => equation.group

\lemma grequation143{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (((x4 G.* x4) G.* (G.inverse x4)) G.* ((x5 G.* (G.inverse x5)) G.* (G.inverse x4))) => equation.group

\lemma grequation144{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x2 G.* ((G.inverse x2) G.* (x3 G.* (G.inverse x3)))) => equation.group

\lemma grequation145{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x7 G.* ((G.inverse x7) G.* (x4 G.* (((G.inverse x4) G.* x2) G.* (G.inverse x2))))) G.* (x6 G.* (x6 G.* (G.inverse x6)))) = ((x6 G.* x2) G.* (G.inverse x2)) => equation.group

\lemma grequation146{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x0 = ((((x0 G.* x0) G.* (x3 G.* x2)) G.* (G.inverse x2)) G.* ((G.inverse x3) G.* (G.inverse x0))) => equation.group

\lemma grequation147{G : Group}(x0 x1 x2 x3 : G): x3 = x3 => equation.group

\lemma grequation148{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x7 G.* (G.inverse x7)) = (x2 G.* (((x0 G.* x4) G.* ((G.inverse x4) G.* (G.inverse x0))) G.* (G.inverse x2))) => equation.group

\lemma grequation149{G : Group}(x0 x1 x2 x3 x4 : G): (x4 G.* ((G.inverse x4) G.* x3)) = (x3 G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation150{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (((x8 G.* (G.inverse x8)) G.* (x2 G.* (x2 G.* x2))) G.* ((((G.inverse x2) G.* (G.inverse x2)) G.* ((G.inverse x2) G.* x1)) G.* (G.inverse x1))) => equation.group

\lemma grequation151{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x2 G.* ((G.inverse x2) G.* x5)) G.* (((G.inverse x5) G.* x4) G.* x3)) = ((x4 G.* x3) G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation152{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x6 G.* x1) G.* ((((G.inverse x1) G.* (G.inverse x6)) G.* x8) G.* (((G.inverse x8) G.* (x8 G.* (G.inverse x8))) G.* (x7 G.* (((G.inverse x7) G.* (x6 G.* x3)) G.* x9))))) = (x6 G.* (x3 G.* x9)) => equation.group

\lemma grequation153{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x0 = ((((((x4 G.* x5) G.* (G.inverse x5)) G.* x4) G.* (G.inverse x4)) G.* ((x6 G.* (G.inverse x6)) G.* (G.inverse x4))) G.* x0) => equation.group

\lemma grequation154{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = ((x4 G.* (x7 G.* (G.inverse x7))) G.* (G.inverse x4)) => equation.group

\lemma grequation155{G : Group}(x0 x1 : G): ((((x1 G.* ((G.inverse x1) G.* (x1 G.* (G.inverse x1)))) G.* x1) G.* (x1 G.* x1)) G.* x1) = ((x1 G.* (x1 G.* ((x1 G.* x1) G.* x0))) G.* (G.inverse x0)) => equation.group

\lemma grequation156{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x9 = ((x7 G.* x4) G.* ((G.inverse x4) G.* ((G.inverse x7) G.* x9))) => equation.group

\lemma grequation157{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x5 = (x4 G.* ((G.inverse x4) G.* x5)) => equation.group

\lemma grequation158{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = (x6 G.* (((G.inverse x6) G.* (x0 G.* x4)) G.* (G.inverse x4))) => equation.group

\lemma grequation159{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x10 = x10 => equation.group

\lemma grequation160{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x5 G.* ((G.inverse x5) G.* x7)) G.* x2) = (((x7 G.* x8) G.* (G.inverse x8)) G.* x2) => equation.group

\lemma grequation161{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x0 G.* x1) = (x0 G.* x1) => equation.group

\lemma grequation162{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x1 G.* (x9 G.* ((G.inverse x9) G.* (G.inverse x1)))) => equation.group

\lemma grequation163{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x3 G.* (G.inverse x3)) G.* (x9 G.* x2)) G.* ((((G.inverse x2) G.* ((G.inverse x9) G.* x7)) G.* (x0 G.* x3)) G.* ((G.inverse x3) G.* (G.inverse x0)))) = ((x10 G.* (G.inverse x10)) G.* ((x7 G.* x9) G.* (G.inverse x9))) => equation.group

\lemma grequation164{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* (((G.inverse x3) G.* x0) G.* ((G.inverse x0) G.* x2))) = ((((x3 G.* (G.inverse x3)) G.* x1) G.* (G.inverse x1)) G.* (x3 G.* ((((G.inverse x3) G.* x2) G.* (x1 G.* (G.inverse x1))) G.* (((G.inverse x2) G.* x5) G.* (((G.inverse x5) G.* x4) G.* ((G.inverse x4) G.* x2)))))) => equation.group

\lemma grequation165{G : Group}(x0 x1 : G): x0 = (x1 G.* (((G.inverse x1) G.* (x0 G.* x0)) G.* (G.inverse x0))) => equation.group

\lemma grequation166{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((((x9 G.* ((G.inverse x9) G.* x1)) G.* (G.inverse x1)) G.* (x4 G.* x4)) G.* (G.inverse x4)) = x4 => equation.group

\lemma grequation167{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x4 G.* (G.inverse x4)) G.* x5) = (((x0 G.* (x5 G.* (G.inverse x5))) G.* (((G.inverse x0) G.* x2) G.* x4)) G.* (((G.inverse x4) G.* (((G.inverse x2) G.* x2) G.* ((G.inverse x2) G.* (x5 G.* (x5 G.* ((G.inverse x5) G.* x2)))))) G.* (G.inverse x2))) => equation.group

\lemma grequation168{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((((x4 G.* x1) G.* (G.inverse x1)) G.* ((G.inverse x4) G.* x3)) G.* ((G.inverse x3) G.* (x0 G.* x0))) G.* (G.inverse x0)) = x0 => equation.group

\lemma grequation169{G : Group}(x0 x1 x2 x3 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation170{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation171{G : Group}(x0 x1 : G): (x1 G.* (G.inverse x1)) = (((x0 G.* x1) G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x1))) G.* (G.inverse x0)) => equation.group

\lemma grequation172{G : Group}(x0 x1 : G): ((x0 G.* (G.inverse x0)) G.* x1) = (((x1 G.* x0) G.* (G.inverse x0)) G.* ((G.inverse x1) G.* x1)) => equation.group

\lemma grequation173{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x5 G.* x12) = (x5 G.* x12) => equation.group

\lemma grequation174{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation175{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x9 = ((x6 G.* (x0 G.* x0)) G.* (((G.inverse x0) G.* (G.inverse x0)) G.* (((G.inverse x6) G.* x9) G.* (x10 G.* (G.inverse x10))))) => equation.group

\lemma grequation176{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x6 = ((x2 G.* (G.inverse x2)) G.* x6) => equation.group

\lemma grequation177{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (((((x3 G.* (G.inverse x3)) G.* (x3 G.* x1)) G.* ((G.inverse x1) G.* ((G.inverse x3) G.* x5))) G.* x1) G.* ((G.inverse x1) G.* (G.inverse x5))) => equation.group

\lemma grequation178{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x10 G.* (G.inverse x10)) => equation.group

\lemma grequation179{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x3 G.* (x4 G.* ((G.inverse x4) G.* (G.inverse x3)))) => equation.group

\lemma grequation180{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x11 = ((x11 G.* ((x6 G.* x10) G.* (x4 G.* (G.inverse x4)))) G.* ((G.inverse x10) G.* (G.inverse x6))) => equation.group

\lemma grequation181{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x1 = (x1 G.* (x13 G.* (G.inverse x13))) => equation.group

\lemma grequation182{G : Group}(x0 x1 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation183{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x4 G.* (G.inverse x4)) G.* x2) G.* (((x0 G.* x3) G.* (G.inverse x3)) G.* (x2 G.* ((G.inverse x2) G.* (G.inverse x0))))) = x2 => equation.group

\lemma grequation184{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((((((x1 G.* x8) G.* x5) G.* x0) G.* x4) G.* (x9 G.* x9)) G.* (((x4 G.* (x4 G.* (G.inverse x4))) G.* (((G.inverse x4) G.* (G.inverse x9)) G.* (G.inverse x9))) G.* (G.inverse x4))) = (x1 G.* (x8 G.* (x5 G.* x0))) => equation.group

\lemma grequation185{G : Group}(x0 x1 x2 x3 x4 : G): (x1 G.* x0) = (((x1 G.* x0) G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation186{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation187{G : Group}(x0 x1 x2 x3 : G): x0 = x0 => equation.group

\lemma grequation188{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x1 = x1 => equation.group

\lemma grequation189{G : Group}(x0 x1 x2 x3 x4 : G): ((x2 G.* (((G.inverse x2) G.* x2) G.* (G.inverse x2))) G.* ((x4 G.* (G.inverse x4)) G.* ((x0 G.* (G.inverse x0)) G.* ((x2 G.* (G.inverse x2)) G.* x3)))) = ((x0 G.* (G.inverse x0)) G.* x3) => equation.group

\lemma grequation190{G : Group}(x0 x1 x2 x3 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation191{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x9 G.* (G.inverse x9)) = (x2 G.* ((x11 G.* (G.inverse x11)) G.* (G.inverse x2))) => equation.group

\lemma grequation192{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation193{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation194{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x8 G.* x5) G.* (G.inverse x5)) = (((x1 G.* (G.inverse x1)) G.* (x5 G.* (G.inverse x5))) G.* (((x3 G.* (G.inverse x3)) G.* (x8 G.* x7)) G.* (G.inverse x7))) => equation.group

\lemma grequation195{G : Group}(x0 x1 : G): x0 = x0 => equation.group

\lemma grequation196{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x7 G.* (x1 G.* x4)) = (((x7 G.* x1) G.* x4) G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation197{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x11 G.* x0) = ((((x11 G.* x0) G.* (x8 G.* (G.inverse x8))) G.* x4) G.* (G.inverse x4)) => equation.group

\lemma grequation198{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x8 G.* x6) G.* (G.inverse x6)) G.* ((G.inverse x8) G.* x6)) = ((x6 G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation199{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((((x1 G.* (G.inverse x1)) G.* x5) G.* x6) G.* (x2 G.* (x4 G.* (G.inverse x4)))) G.* ((((G.inverse x2) G.* ((G.inverse x6) G.* (G.inverse x5))) G.* x4) G.* (x3 G.* (G.inverse x3)))) = x4 => equation.group

\lemma grequation200{G : Group}(x0 x1 x2 x3 x4 x5 : G): x5 = (x5 G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation201{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x12 = ((((x12 G.* (x1 G.* x9)) G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x9))) G.* ((G.inverse x1) G.* (((G.inverse x12) G.* x12) G.* x3))) G.* (((G.inverse x3) G.* x0) G.* ((G.inverse x0) G.* (x5 G.* (G.inverse x5))))) => equation.group

\lemma grequation202{G : Group}(x0 x1 x2 : G): G.ide = ((x0 G.* (G.inverse x0)) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation203{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x14 G.* x13) = ((((x14 G.* x13) G.* x13) G.* (x8 G.* (((x0 G.* (G.inverse x0)) G.* x10) G.* (G.inverse x10)))) G.* ((G.inverse x8) G.* (G.inverse x13))) => equation.group

\lemma grequation204{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = ((x2 G.* x4) G.* ((G.inverse x4) G.* (G.inverse x2))) => equation.group

\lemma grequation205{G : Group}(x0 x1 x2 x3 : G): x1 = (((x1 G.* x0) G.* (G.inverse x0)) G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation206{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x5 G.* (G.inverse x5)) G.* x1) = (x1 G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation207{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x3 G.* (x2 G.* x3)) G.* (x8 G.* (G.inverse x8))) = (((x8 G.* (G.inverse x8)) G.* x3) G.* (x2 G.* x3)) => equation.group

\lemma grequation208{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation209{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x8 G.* (x3 G.* ((G.inverse x3) G.* x5))) = (x8 G.* x5) => equation.group

\lemma grequation210{G : Group}(x0 x1 x2 : G): (x2 G.* ((x0 G.* x1) G.* (G.inverse x1))) = ((x2 G.* x0) G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation211{G : Group}(x0 x1 x2 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation212{G : Group}(x0 x1 x2 x3 x4 : G): x3 = (((x3 G.* x3) G.* x1) G.* ((G.inverse x1) G.* (G.inverse x3))) => equation.group

\lemma grequation213{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x5 G.* ((x10 G.* x10) G.* (x14 G.* (G.inverse x14)))) = (x5 G.* (x10 G.* x10)) => equation.group

\lemma grequation214{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation215{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x4 G.* ((G.inverse x4) G.* x6)) G.* (x3 G.* ((G.inverse x3) G.* x6))) G.* (((x2 G.* ((G.inverse x2) G.* x1)) G.* (x0 G.* x0)) G.* (((G.inverse x0) G.* ((G.inverse x0) G.* (G.inverse x1))) G.* (G.inverse x6)))) = x6 => equation.group

\lemma grequation216{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation217{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x11 G.* ((G.inverse x11) G.* x8)) = (x11 G.* ((G.inverse x11) G.* x8)) => equation.group

\lemma grequation218{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((((x12 G.* ((G.inverse x12) G.* x4)) G.* (G.inverse x4)) G.* x11) G.* (G.inverse x11)) = (x10 G.* ((G.inverse x10) G.* (x10 G.* (((G.inverse x10) G.* x7) G.* (G.inverse x7))))) => equation.group

\lemma grequation219{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation220{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x0 G.* ((x6 G.* (G.inverse x6)) G.* (G.inverse x0))) G.* (x0 G.* (x8 G.* (G.inverse x8)))) = x0 => equation.group

\lemma grequation221{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x3 G.* (G.inverse x3)) G.* x7) = (x7 G.* (x8 G.* (G.inverse x8))) => equation.group

\lemma grequation222{G : Group}(x0 x1 x2 x3 : G): ((((x3 G.* ((G.inverse x3) G.* x0)) G.* (G.inverse x0)) G.* (x0 G.* x3)) G.* (((G.inverse x3) G.* (G.inverse x0)) G.* (x3 G.* (G.inverse x3)))) = (((x1 G.* (G.inverse x1)) G.* ((x1 G.* (G.inverse x1)) G.* (x2 G.* (G.inverse x2)))) G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation223{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x1 G.* (G.inverse x1)) = ((x8 G.* x4) G.* ((G.inverse x4) G.* (G.inverse x8))) => equation.group

\lemma grequation224{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x6 = x6 => equation.group

\lemma grequation225{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation226{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x5 = (((x8 G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x8)) G.* x5) => equation.group

\lemma grequation227{G : Group}(x0 x1 : G): x1 = ((x1 G.* (G.inverse x1)) G.* x1) => equation.group

\lemma grequation228{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x5 G.* x3) = (x5 G.* x3) => equation.group

\lemma grequation229{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((x12 G.* x7) G.* x0) G.* ((((G.inverse x0) G.* (G.inverse x7)) G.* ((G.inverse x12) G.* x6)) G.* (((G.inverse x6) G.* ((x6 G.* (G.inverse x6)) G.* x9)) G.* (G.inverse x9)))) => equation.group

\lemma grequation230{G : Group}(x0 x1 x2 x3 x4 : G): (((x0 G.* x1) G.* x4) G.* ((G.inverse x4) G.* (G.inverse x1))) = x0 => equation.group

\lemma grequation231{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x1 G.* x3) G.* x5) = (x1 G.* (x3 G.* x5)) => equation.group

\lemma grequation232{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = x0 => equation.group

\lemma grequation233{G : Group}(x0 x1 x2 : G): (x0 G.* x2) = (((x0 G.* x2) G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation234{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x4 = ((x4 G.* ((x4 G.* x9) G.* (G.inverse x9))) G.* (G.inverse x4)) => equation.group

\lemma grequation235{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x9 G.* x9) = (x9 G.* x9) => equation.group

\lemma grequation236{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x7 G.* ((x5 G.* (G.inverse x5)) G.* x5)) G.* (x4 G.* x0)) G.* ((G.inverse x0) G.* ((G.inverse x4) G.* x5))) = (x7 G.* (x5 G.* x5)) => equation.group

\lemma grequation237{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation238{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x4 = ((x4 G.* x5) G.* (G.inverse x5)) => equation.group

\lemma grequation239{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x10 G.* (G.inverse x10)) = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation240{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x9 = (((x1 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x1) G.* x9)) => equation.group

\lemma grequation241{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x6 = ((x8 G.* x6) G.* (((G.inverse x6) G.* ((G.inverse x8) G.* (x9 G.* (G.inverse x9)))) G.* ((x6 G.* x12) G.* (G.inverse x12)))) => equation.group

\lemma grequation242{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x7 = x7 => equation.group

\lemma grequation243{G : Group}(x0 x1 x2 : G): (x2 G.* x1) = (x2 G.* x1) => equation.group

\lemma grequation244{G : Group}(x0 x1 x2 x3 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation245{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x5 G.* (x4 G.* (G.inverse x4))) G.* (((G.inverse x5) G.* x12) G.* (x12 G.* (G.inverse x12)))) = x12 => equation.group

\lemma grequation246{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x2 G.* x1) G.* ((G.inverse x1) G.* ((G.inverse x2) G.* x4))) = ((x3 G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x3)))) G.* ((x3 G.* (G.inverse x3)) G.* x4)) => equation.group

\lemma grequation247{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x5 G.* (x10 G.* ((G.inverse x10) G.* ((G.inverse x5) G.* x4)))) G.* ((x8 G.* (G.inverse x8)) G.* x9)) = (((x6 G.* (G.inverse x6)) G.* x4) G.* ((x8 G.* x6) G.* ((G.inverse x6) G.* ((G.inverse x8) G.* x9)))) => equation.group

\lemma grequation248{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x7 G.* ((G.inverse x7) G.* x3)) = x3 => equation.group

\lemma grequation249{G : Group}(x0 x1 x2 : G): x0 = x0 => equation.group

\lemma grequation250{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x3 = (x3 G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation251{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((x11 G.* (G.inverse x11)) G.* (x9 G.* (G.inverse x9))) => equation.group

\lemma grequation252{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((x10 G.* ((G.inverse x10) G.* x12)) G.* (((G.inverse x12) G.* (x2 G.* x4)) G.* (G.inverse x4))) G.* (G.inverse x2)) => equation.group

\lemma grequation253{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x9 G.* (((G.inverse x9) G.* (x10 G.* x11)) G.* (G.inverse x11))) = ((x8 G.* (G.inverse x8)) G.* (x11 G.* ((G.inverse x11) G.* x10))) => equation.group

\lemma grequation254{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x8 = x8 => equation.group

\lemma grequation255{G : Group}(x0 x1 x2 : G): (x0 G.* ((G.inverse x0) G.* (x0 G.* (G.inverse x0)))) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation256{G : Group}(x0 x1 : G): ((x1 G.* x0) G.* (x1 G.* (G.inverse x1))) = (x1 G.* x0) => equation.group

\lemma grequation257{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((((x5 G.* (G.inverse x5)) G.* (x7 G.* x9)) G.* (x12 G.* (G.inverse x12))) G.* ((G.inverse x9) G.* x3)) G.* (x13 G.* (G.inverse x13))) = (x7 G.* x3) => equation.group

\lemma grequation258{G : Group}(x0 x1 x2 : G): x2 = x2 => equation.group

\lemma grequation259{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x6 G.* ((G.inverse x6) G.* x6)) G.* ((G.inverse x6) G.* x2)) = ((((x8 G.* (x4 G.* x0)) G.* ((G.inverse x0) G.* (x4 G.* (G.inverse x4)))) G.* (G.inverse x4)) G.* ((G.inverse x8) G.* x2)) => equation.group

\lemma grequation260{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x9 G.* (G.inverse x9)) G.* x0) = x0 => equation.group

\lemma grequation261{G : Group}(x0 x1 : G): ((x0 G.* (G.inverse x0)) G.* x0) = x0 => equation.group

\lemma grequation262{G : Group}(x0 x1 x2 x3 : G): x3 = x3 => equation.group

\lemma grequation263{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x1 = x1 => equation.group

\lemma grequation264{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x6 G.* (G.inverse x6)) = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation265{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x8 G.* (G.inverse x8)) = (x9 G.* (((x0 G.* (x0 G.* (G.inverse x0))) G.* x2) G.* ((G.inverse x2) G.* ((G.inverse x0) G.* (G.inverse x9))))) => equation.group

\lemma grequation266{G : Group}(x0 x1 x2 x3 : G): ((((x1 G.* (G.inverse x1)) G.* x1) G.* x0) G.* (G.inverse x0)) = x1 => equation.group

\lemma grequation267{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x4 G.* (G.inverse x4)) = (((x2 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x2)) => equation.group

\lemma grequation268{G : Group}(x0 x1 x2 x3 : G): x1 = x1 => equation.group

\lemma grequation269{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x8 = ((x8 G.* x1) G.* ((x2 G.* x6) G.* (((G.inverse x6) G.* (G.inverse x2)) G.* (G.inverse x1)))) => equation.group

\lemma grequation270{G : Group}(x0 x1 x2 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation271{G : Group}(x0 x1 : G): (x1 G.* (x1 G.* ((G.inverse x1) G.* x1))) = (((x1 G.* x1) G.* (((x1 G.* x0) G.* x0) G.* (x1 G.* x1))) G.* (((x1 G.* ((G.inverse x1) G.* ((G.inverse x1) G.* (G.inverse x1)))) G.* (((G.inverse x0) G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x0))) G.* (G.inverse x1))) => equation.group

\lemma grequation272{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x4 G.* (x5 G.* x5)) G.* (x1 G.* (G.inverse x1))) = (((x5 G.* (G.inverse x5)) G.* x4) G.* (((G.inverse x4) G.* (x4 G.* x5)) G.* x5)) => equation.group

\lemma grequation273{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation274{G : Group}(x0 x1 : G): ((x0 G.* ((G.inverse x0) G.* x1)) G.* ((G.inverse x1) G.* x1)) = (x1 G.* ((G.inverse x1) G.* x1)) => equation.group

\lemma grequation275{G : Group}(x0 x1 x2 x3 : G): (x0 G.* (x1 G.* ((G.inverse x1) G.* ((G.inverse x0) G.* x3)))) = x3 => equation.group

\lemma grequation276{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* x4) = ((((x3 G.* ((G.inverse x3) G.* x3)) G.* x0) G.* (G.inverse x0)) G.* x4) => equation.group

\lemma grequation277{G : Group}(x0 x1 : G): ((x0 G.* (x1 G.* (x1 G.* (G.inverse x1)))) G.* (G.inverse x1)) = x0 => equation.group

\lemma grequation278{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x0 G.* ((x7 G.* x5) G.* ((G.inverse x5) G.* (G.inverse x7)))) = ((x9 G.* (x8 G.* (G.inverse x8))) G.* ((G.inverse x9) G.* x0)) => equation.group

\lemma grequation279{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x3 G.* x0) G.* (G.inverse x0)) = ((x3 G.* (x5 G.* x0)) G.* ((G.inverse x0) G.* (G.inverse x5))) => equation.group

\lemma grequation280{G : Group}(x0 x1 : G): x1 = x1 => equation.group

\lemma grequation281{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x9 G.* x1) G.* (G.inverse x1)) = x9 => equation.group

\lemma grequation282{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation283{G : Group}(x0 x1 x2 x3 : G): ((((x3 G.* (G.inverse x3)) G.* x3) G.* (G.inverse x3)) G.* ((x3 G.* (G.inverse x3)) G.* ((x2 G.* x1) G.* x0))) = (x2 G.* (x1 G.* x0)) => equation.group

\lemma grequation284{G : Group}(x0 x1 x2 x3 : G): ((((x1 G.* x2) G.* (G.inverse x2)) G.* (G.inverse x1)) G.* (x2 G.* (x2 G.* x0))) = (x2 G.* (x2 G.* x0)) => equation.group

\lemma grequation285{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x5 G.* (G.inverse x5)) G.* x13) = x13 => equation.group

\lemma grequation286{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x9 G.* x5) G.* (x6 G.* x6)) = ((((x9 G.* x5) G.* (x6 G.* x6)) G.* x0) G.* (G.inverse x0)) => equation.group

\lemma grequation287{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((((x1 G.* ((G.inverse x1) G.* x13)) G.* ((G.inverse x13) G.* x9)) G.* ((G.inverse x9) G.* (x9 G.* x6))) G.* (((G.inverse x6) G.* (G.inverse x9)) G.* (x3 G.* (G.inverse x3)))) => equation.group

\lemma grequation288{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation289{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((((x2 G.* (G.inverse x2)) G.* x4) G.* (G.inverse x4)) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation290{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x9 G.* ((((G.inverse x9) G.* x1) G.* (x10 G.* x11)) G.* (((G.inverse x11) G.* x2) G.* x11))) = (((x1 G.* x10) G.* (x2 G.* (x11 G.* x3))) G.* (G.inverse x3)) => equation.group

\lemma grequation291{G : Group}(x0 x1 x2 x3 : G): ((x1 G.* x3) G.* (x1 G.* (((G.inverse x1) G.* ((G.inverse x3) G.* (G.inverse x1))) G.* x2))) = (x2 G.* (x0 G.* (x2 G.* ((G.inverse x2) G.* (G.inverse x0))))) => equation.group

\lemma grequation292{G : Group}(x0 x1 x2 x3 : G): x1 = x1 => equation.group

\lemma grequation293{G : Group}(x0 x1 x2 x3 : G): x0 = x0 => equation.group

\lemma grequation294{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = ((x2 G.* x4) G.* ((G.inverse x4) G.* (G.inverse x2))) => equation.group

\lemma grequation295{G : Group}(x0 x1 x2 x3 x4 x5 : G): x5 = (((x2 G.* x2) G.* (G.inverse x2)) G.* ((G.inverse x2) G.* x5)) => equation.group

\lemma grequation296{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x1 G.* (G.inverse x1)) G.* x4) = x4 => equation.group

\lemma grequation297{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (((x1 G.* x0) G.* x3) G.* (x2 G.* (G.inverse x2))) = ((x1 G.* ((x0 G.* x3) G.* x12)) G.* (G.inverse x12)) => equation.group

\lemma grequation298{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x6 G.* (x3 G.* (G.inverse x3))) G.* (((G.inverse x6) G.* (x3 G.* x1)) G.* (x4 G.* x5))) G.* (((G.inverse x5) G.* (G.inverse x4)) G.* ((G.inverse x1) G.* x1))) = ((x1 G.* (G.inverse x1)) G.* (((x0 G.* (G.inverse x0)) G.* x3) G.* x1)) => equation.group

\lemma grequation299{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x0 G.* x2) G.* ((((G.inverse x2) G.* (x0 G.* (G.inverse x0))) G.* x9) G.* ((G.inverse x9) G.* (G.inverse x0)))) = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation300{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x0 G.* x7) G.* ((G.inverse x7) G.* ((G.inverse x0) G.* x2))) G.* ((G.inverse x2) G.* x4)) = x4 => equation.group

\lemma grequation301{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x5 G.* (x6 G.* (G.inverse x6))) = x5 => equation.group

\lemma grequation302{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x8 = ((x8 G.* ((x12 G.* (G.inverse x12)) G.* x9)) G.* (G.inverse x9)) => equation.group

\lemma grequation303{G : Group}(x0 x1 : G): (x1 G.* ((x0 G.* x0) G.* (G.inverse x0))) = ((x1 G.* (G.inverse x1)) G.* (((x1 G.* (G.inverse x1)) G.* (x1 G.* x0)) G.* (((G.inverse x0) G.* ((x0 G.* x1) G.* x1)) G.* ((G.inverse x1) G.* (G.inverse x1))))) => equation.group

\lemma grequation304{G : Group}(x0 x1 x2 x3 : G): x2 = x2 => equation.group

\lemma grequation305{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation306{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (((x0 G.* (G.inverse x0)) G.* x2) G.* (G.inverse x2)) => equation.group

\lemma grequation307{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x2 G.* ((G.inverse x2) G.* x4)) G.* ((x0 G.* (x1 G.* (G.inverse x1))) G.* (G.inverse x0))) = (x4 G.* ((x4 G.* (x4 G.* (((G.inverse x4) G.* x1) G.* (G.inverse x1)))) G.* (G.inverse x4))) => equation.group

\lemma grequation308{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x7 = ((x2 G.* (G.inverse x2)) G.* x7) => equation.group

\lemma grequation309{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x7 G.* (G.inverse x7)) G.* x11) = ((x11 G.* (G.inverse x11)) G.* x11) => equation.group

\lemma grequation310{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (((x2 G.* x4) G.* (x4 G.* x4)) G.* (((x2 G.* (G.inverse x2)) G.* x8) G.* (((G.inverse x8) G.* (x3 G.* (G.inverse x3))) G.* ((((G.inverse x4) G.* ((G.inverse x4) G.* (G.inverse x4))) G.* x0) G.* ((G.inverse x0) G.* (G.inverse x2)))))) => equation.group

\lemma grequation311{G : Group}(x0 x1 x2 x3 : G): (x0 G.* (G.inverse x0)) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation312{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation313{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x0 = (x6 G.* ((G.inverse x6) G.* x0)) => equation.group

\lemma grequation314{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x12 = ((((x1 G.* (G.inverse x1)) G.* x0) G.* (x11 G.* ((G.inverse x11) G.* ((x7 G.* (G.inverse x7)) G.* x0)))) G.* ((((G.inverse x0) G.* (x9 G.* (G.inverse x9))) G.* x2) G.* ((G.inverse x2) G.* ((x6 G.* (G.inverse x6)) G.* ((G.inverse x0) G.* x12))))) => equation.group

\lemma grequation315{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation316{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x2 G.* ((G.inverse x2) G.* (x6 G.* (G.inverse x6)))) = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation317{G : Group}(x0 x1 : G): ((x0 G.* (x0 G.* (x0 G.* (G.inverse x0)))) G.* x0) = (x0 G.* (x0 G.* x0)) => equation.group

\lemma grequation318{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((((((x5 G.* (G.inverse x5)) G.* x6) G.* (G.inverse x6)) G.* (x3 G.* (G.inverse x3))) G.* (x3 G.* (G.inverse x3))) G.* x4) = (((x0 G.* (x5 G.* ((G.inverse x5) G.* ((G.inverse x0) G.* x2)))) G.* ((x2 G.* (G.inverse x2)) G.* x0)) G.* ((G.inverse x0) G.* ((G.inverse x2) G.* x4))) => equation.group

\lemma grequation319{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x2 G.* ((x4 G.* (G.inverse x4)) G.* (G.inverse x2))) = (((x7 G.* x1) G.* ((x0 G.* (G.inverse x0)) G.* ((G.inverse x1) G.* (G.inverse x7)))) G.* (x2 G.* (((G.inverse x2) G.* x8) G.* (G.inverse x8)))) => equation.group

\lemma grequation320{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x12 G.* (G.inverse x12)) = (((x3 G.* x10) G.* (G.inverse x10)) G.* (G.inverse x3)) => equation.group

\lemma grequation321{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation322{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x5 = x5 => equation.group

\lemma grequation323{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x4 = ((x6 G.* (G.inverse x6)) G.* x4) => equation.group

\lemma grequation324{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x3 = ((x3 G.* (x1 G.* (G.inverse x1))) G.* (x11 G.* (G.inverse x11))) => equation.group

\lemma grequation325{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x0 G.* x2) = ((x4 G.* (G.inverse x4)) G.* ((x0 G.* (x3 G.* (G.inverse x3))) G.* ((G.inverse x0) G.* (x0 G.* x2)))) => equation.group

\lemma grequation326{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((x8 G.* (G.inverse x8)) G.* (x7 G.* (G.inverse x7))) => equation.group

\lemma grequation327{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((x2 G.* x6) G.* ((G.inverse x6) G.* (G.inverse x2))) => equation.group

\lemma grequation328{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x4 = (((x8 G.* x1) G.* ((G.inverse x1) G.* (G.inverse x8))) G.* ((x0 G.* (G.inverse x0)) G.* x4)) => equation.group

\lemma grequation329{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x0 G.* (G.inverse x0)) = (((x6 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x6)) => equation.group

\lemma grequation330{G : Group}(x0 x1 x2 : G): G.ide = ((x1 G.* x1) G.* (x0 G.* ((((G.inverse x0) G.* ((((G.inverse x1) G.* x2) G.* (G.inverse x2)) G.* x1)) G.* ((G.inverse x1) G.* (x1 G.* (((G.inverse x1) G.* (G.inverse x1)) G.* x0)))) G.* (G.inverse x0)))) => equation.group

\lemma grequation331{G : Group}(x0 x1 x2 x3 x4 : G): (((x3 G.* x0) G.* ((x1 G.* (G.inverse x1)) G.* x3)) G.* (((G.inverse x3) G.* (G.inverse x0)) G.* (x4 G.* (G.inverse x4)))) = x3 => equation.group

\lemma grequation332{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x4 G.* x7) G.* (G.inverse x7)) = x4 => equation.group

\lemma grequation333{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation334{G : Group}(x0 x1 x2 x3 x4 : G): (x3 G.* x0) = ((((x3 G.* x0) G.* x0) G.* x1) G.* ((((x0 G.* x0) G.* (G.inverse x0)) G.* ((G.inverse x0) G.* (G.inverse x1))) G.* (G.inverse x0))) => equation.group

\lemma grequation335{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x2 G.* (G.inverse x2)) G.* x0) G.* (x8 G.* (G.inverse x8))) = x0 => equation.group

\lemma grequation336{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x7 G.* ((G.inverse x7) G.* (x13 G.* (G.inverse x13)))) => equation.group

\lemma grequation337{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((x5 G.* ((G.inverse x5) G.* x4)) G.* (((G.inverse x4) G.* x8) G.* (G.inverse x8))) => equation.group

\lemma grequation338{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x12 G.* (G.inverse x12)) => equation.group

\lemma grequation339{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (((((x0 G.* (G.inverse x0)) G.* x7) G.* ((x9 G.* x0) G.* ((x2 G.* (G.inverse x2)) G.* (x4 G.* (G.inverse x4))))) G.* ((G.inverse x0) G.* (G.inverse x9))) G.* (x6 G.* (((G.inverse x6) G.* (G.inverse x7)) G.* x2))) = x2 => equation.group

\lemma grequation340{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x5 G.* x5) G.* x0) = (((x11 G.* (G.inverse x11)) G.* ((x9 G.* (G.inverse x9)) G.* x5)) G.* (((x5 G.* x8) G.* (G.inverse x8)) G.* x0)) => equation.group

\lemma grequation341{G : Group}(x0 x1 x2 x3 x4 : G): ((x3 G.* ((G.inverse x3) G.* x1)) G.* (G.inverse x1)) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation342{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation343{G : Group}(x0 x1 x2 x3 : G): (x0 G.* ((G.inverse x0) G.* x3)) = x3 => equation.group

\lemma grequation344{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x7 = x7 => equation.group

\lemma grequation345{G : Group}(x0 x1 x2 x3 x4 : G): (x3 G.* (x3 G.* (((G.inverse x3) G.* (G.inverse x3)) G.* x4))) = ((x1 G.* (G.inverse x1)) G.* x4) => equation.group

\lemma grequation346{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (((x4 G.* (G.inverse x4)) G.* x5) G.* (G.inverse x5)) = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation347{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((x2 G.* ((G.inverse x2) G.* x10)) G.* (G.inverse x10)) => equation.group

\lemma grequation348{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x7 G.* (x2 G.* ((G.inverse x2) G.* x2))) = (x7 G.* x2) => equation.group

\lemma grequation349{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x4 G.* (((G.inverse x4) G.* (x6 G.* ((G.inverse x6) G.* x3))) G.* (G.inverse x3))) => equation.group

\lemma grequation350{G : Group}(x0 x1 x2 : G): ((x1 G.* x2) G.* ((((G.inverse x2) G.* (x1 G.* (G.inverse x1))) G.* ((G.inverse x1) G.* x1)) G.* (((G.inverse x1) G.* x1) G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x1))))) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation351{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x10 = ((x0 G.* (G.inverse x0)) G.* x10) => equation.group

\lemma grequation352{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x3 G.* x7) = ((((x9 G.* x4) G.* (x7 G.* x6)) G.* (((G.inverse x6) G.* (((G.inverse x7) G.* (G.inverse x4)) G.* (G.inverse x9))) G.* x3)) G.* x7) => equation.group

\lemma grequation353{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x5 G.* (x10 G.* (G.inverse x10))) G.* (((G.inverse x5) G.* (x7 G.* x9)) G.* (G.inverse x9))) = x7 => equation.group

\lemma grequation354{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x13 = (((x9 G.* (x3 G.* x8)) G.* (G.inverse x8)) G.* ((x1 G.* (G.inverse x1)) G.* ((G.inverse x3) G.* ((G.inverse x9) G.* x13)))) => equation.group

\lemma grequation355{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation356{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x0 G.* (x0 G.* x7)) = (x0 G.* ((x0 G.* x1) G.* (((G.inverse x1) G.* (x2 G.* (G.inverse x2))) G.* x7))) => equation.group

\lemma grequation357{G : Group}(x0 x1 x2 : G): (x2 G.* (x2 G.* (x0 G.* x1))) = ((x2 G.* (x2 G.* x0)) G.* ((x1 G.* x0) G.* (G.inverse x0))) => equation.group

\lemma grequation358{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((((x9 G.* (x6 G.* (G.inverse x6))) G.* ((G.inverse x9) G.* (x5 G.* (G.inverse x5)))) G.* (x2 G.* (G.inverse x2))) G.* x4) = (((x4 G.* (x4 G.* x4)) G.* (G.inverse x4)) G.* (G.inverse x4)) => equation.group

\lemma grequation359{G : Group}(x0 x1 x2 x3 : G): x3 = ((x2 G.* (G.inverse x2)) G.* x3) => equation.group

\lemma grequation360{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation361{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x2 G.* ((G.inverse x2) G.* (x5 G.* ((G.inverse x5) G.* x3)))) = ((x1 G.* (G.inverse x1)) G.* ((x4 G.* ((G.inverse x4) G.* x0)) G.* ((G.inverse x0) G.* x3))) => equation.group

\lemma grequation362{G : Group}(x0 x1 : G): x1 = (x1 G.* (((x1 G.* x0) G.* ((G.inverse x0) G.* x0)) G.* ((G.inverse x0) G.* ((G.inverse x1) G.* ((G.inverse x1) G.* x1))))) => equation.group

\lemma grequation363{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (((x4 G.* (G.inverse x4)) G.* x7) G.* (G.inverse x7)) => equation.group

\lemma grequation364{G : Group}(x0 x1 x2 x3 x4 : G): x1 = x1 => equation.group

\lemma grequation365{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x10 G.* (x2 G.* x11)) = ((x10 G.* ((x2 G.* ((x11 G.* x1) G.* (x4 G.* x2))) G.* (x9 G.* (G.inverse x9)))) G.* (((G.inverse x2) G.* (G.inverse x4)) G.* (G.inverse x1))) => equation.group

\lemma grequation366{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x1 G.* ((x7 G.* x5) G.* (G.inverse x5))) = ((x1 G.* (x7 G.* x12)) G.* (G.inverse x12)) => equation.group

\lemma grequation367{G : Group}(x0 x1 x2 x3 x4 : G): ((x3 G.* (G.inverse x3)) G.* (x3 G.* x1)) = ((((x2 G.* (G.inverse x2)) G.* x4) G.* (G.inverse x4)) G.* ((((((x4 G.* (G.inverse x4)) G.* x0) G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x0)) G.* (x4 G.* ((G.inverse x4) G.* x3))) G.* x1)) => equation.group

\lemma grequation368{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation369{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x3 G.* ((G.inverse x3) G.* x3)) = x3 => equation.group

\lemma grequation370{G : Group}(x0 x1 x2 x3 : G): (((x1 G.* (G.inverse x1)) G.* (x3 G.* (G.inverse x3))) G.* (x2 G.* (G.inverse x2))) = (x1 G.* ((G.inverse x1) G.* (x3 G.* (G.inverse x3)))) => equation.group

\lemma grequation371{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = (x5 G.* ((x4 G.* ((G.inverse x4) G.* (G.inverse x5))) G.* x0)) => equation.group

\lemma grequation372{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x1 = (x6 G.* ((G.inverse x6) G.* (x9 G.* ((G.inverse x9) G.* x1)))) => equation.group

\lemma grequation373{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x2 G.* (G.inverse x2)) = ((x5 G.* ((G.inverse x5) G.* x3)) G.* (G.inverse x3)) => equation.group

\lemma grequation374{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((x0 G.* (G.inverse x0)) G.* (x6 G.* (G.inverse x6))) => equation.group

\lemma grequation375{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x9 G.* ((G.inverse x9) G.* (x4 G.* x11))) = (x4 G.* x11) => equation.group

\lemma grequation376{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x1 G.* ((G.inverse x1) G.* x3)) G.* (((G.inverse x3) G.* x7) G.* ((G.inverse x7) G.* x9))) G.* x7) = (x9 G.* x7) => equation.group

\lemma grequation377{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x0 G.* (x1 G.* (G.inverse x1))) = x0 => equation.group

\lemma grequation378{G : Group}(x0 x1 x2 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation379{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x6 = x6 => equation.group

\lemma grequation380{G : Group}(x0 x1 x2 x3 : G): x3 = ((x3 G.* x1) G.* (((x3 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x3) G.* (G.inverse x1)))) => equation.group

\lemma grequation381{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation382{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x5 G.* x7) G.* x1) G.* (x7 G.* (G.inverse x7))) = ((x5 G.* x7) G.* x1) => equation.group

\lemma grequation383{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = ((x1 G.* (x6 G.* (G.inverse x6))) G.* (G.inverse x1)) => equation.group

\lemma grequation384{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x9 G.* ((G.inverse x9) G.* x1)) = x1 => equation.group

\lemma grequation385{G : Group}(x0 x1 x2 : G): ((x1 G.* (x2 G.* x2)) G.* ((G.inverse x2) G.* (G.inverse x2))) = x1 => equation.group

\lemma grequation386{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x9 G.* (G.inverse x9)) G.* x9) = (x8 G.* ((G.inverse x8) G.* x9)) => equation.group

\lemma grequation387{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x1 G.* (G.inverse x1)) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation388{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x2 = ((x7 G.* (G.inverse x7)) G.* x2) => equation.group

\lemma grequation389{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x3 G.* ((G.inverse x3) G.* x7)) G.* ((G.inverse x7) G.* (x1 G.* x3))) = ((x1 G.* (x3 G.* x3)) G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x3))) => equation.group

\lemma grequation390{G : Group}(x0 x1 x2 x3 : G): ((x3 G.* (((x0 G.* (G.inverse x0)) G.* (G.inverse x3)) G.* x1)) G.* ((((G.inverse x1) G.* x2) G.* (G.inverse x2)) G.* ((x0 G.* x2) G.* (G.inverse x2)))) = x0 => equation.group

\lemma grequation391{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x0 G.* x2) = ((x0 G.* x3) G.* ((G.inverse x3) G.* x2)) => equation.group

\lemma grequation392{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x5 G.* x11) = (x5 G.* x11) => equation.group

\lemma grequation393{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x2 = ((x0 G.* (G.inverse x0)) G.* x2) => equation.group

\lemma grequation394{G : Group}(x0 x1 : G): (x1 G.* (x1 G.* ((x1 G.* (G.inverse x1)) G.* (x1 G.* (G.inverse x1))))) = (x1 G.* (((G.inverse x1) G.* x0) G.* ((G.inverse x0) G.* (x1 G.* x1)))) => equation.group

\lemma grequation395{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x3 G.* ((G.inverse x3) G.* x3)) = ((x3 G.* (x9 G.* x10)) G.* (((((x3 G.* x8) G.* (G.inverse x8)) G.* (x3 G.* (G.inverse x3))) G.* (G.inverse x3)) G.* ((G.inverse x10) G.* (G.inverse x9)))) => equation.group

\lemma grequation396{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* x2) G.* (x2 G.* (G.inverse x2))) = ((x0 G.* ((x2 G.* x1) G.* (x0 G.* x1))) G.* (((G.inverse x1) G.* (G.inverse x0)) G.* (G.inverse x1))) => equation.group

\lemma grequation397{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* (G.inverse x3)) = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation398{G : Group}(x0 x1 x2 : G): (x0 G.* (x2 G.* (G.inverse x2))) = (x0 G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation399{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x5 G.* x1) = (((x9 G.* x8) G.* ((G.inverse x8) G.* ((G.inverse x9) G.* (x5 G.* (x1 G.* x3))))) G.* ((x7 G.* (G.inverse x7)) G.* (G.inverse x3))) => equation.group

\lemma grequation400{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x4 G.* x2) = (x4 G.* x2) => equation.group

\lemma grequation401{G : Group}(x0 x1 x2 : G): (x0 G.* x1) = (((x0 G.* x1) G.* x1) G.* ((((x0 G.* x0) G.* (G.inverse x0)) G.* ((G.inverse x0) G.* (G.inverse x1))) G.* ((G.inverse x1) G.* x1))) => equation.group

\lemma grequation402{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x5 G.* ((G.inverse x5) G.* x9)) = ((x9 G.* x6) G.* (G.inverse x6)) => equation.group

\lemma grequation403{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x1 G.* (G.inverse x1)) G.* x1) = x1 => equation.group

\lemma grequation404{G : Group}(x0 x1 x2 x3 x4 : G): ((x0 G.* (G.inverse x0)) G.* x0) = (((x3 G.* ((G.inverse x3) G.* x1)) G.* (G.inverse x1)) G.* x0) => equation.group

\lemma grequation405{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x3 G.* x6) G.* ((x0 G.* ((G.inverse x0) G.* x2)) G.* (G.inverse x2))) = (x3 G.* x6) => equation.group

\lemma grequation406{G : Group}(x0 x1 x2 x3 x4 : G): (x4 G.* (x0 G.* ((G.inverse x0) G.* (x3 G.* ((G.inverse x3) G.* (x0 G.* x2)))))) = ((x4 G.* x0) G.* (x0 G.* ((G.inverse x0) G.* x2))) => equation.group

\lemma grequation407{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (((x0 G.* (G.inverse x0)) G.* x3) G.* (((G.inverse x3) G.* x4) G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x4)))) => equation.group

\lemma grequation408{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation409{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x4 = x4 => equation.group

\lemma grequation410{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (((((x3 G.* x11) G.* ((x10 G.* (G.inverse x10)) G.* (G.inverse x11))) G.* (x2 G.* ((G.inverse x2) G.* (G.inverse x3)))) G.* (x6 G.* x10)) G.* ((G.inverse x10) G.* (((x14 G.* (G.inverse x14)) G.* x4) G.* (((G.inverse x4) G.* (G.inverse x6)) G.* (x14 G.* (G.inverse x14)))))) => equation.group

\lemma grequation411{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x7 G.* ((G.inverse x7) G.* x2)) = x2 => equation.group

\lemma grequation412{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((x8 G.* x10) G.* ((G.inverse x10) G.* (G.inverse x8))) G.* (x6 G.* (G.inverse x6))) => equation.group

\lemma grequation413{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x0 G.* (G.inverse x0)) = ((((x1 G.* x7) G.* (x4 G.* ((G.inverse x4) G.* ((G.inverse x7) G.* (x6 G.* (G.inverse x6)))))) G.* ((G.inverse x1) G.* x5)) G.* (G.inverse x5)) => equation.group

\lemma grequation414{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x8 G.* (G.inverse x8)) G.* x5) = x5 => equation.group

\lemma grequation415{G : Group}(x0 x1 x2 x3 x4 : G): x3 = x3 => equation.group

\lemma grequation416{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x2 G.* ((G.inverse x2) G.* x3)) G.* (x1 G.* (((G.inverse x1) G.* (G.inverse x3)) G.* x2))) = (x6 G.* ((G.inverse x6) G.* x2)) => equation.group

\lemma grequation417{G : Group}(x0 x1 x2 x3 x4 : G): ((((x1 G.* x1) G.* (G.inverse x1)) G.* ((G.inverse x1) G.* x2)) G.* (((G.inverse x2) G.* x0) G.* x1)) = (x0 G.* x1) => equation.group

\lemma grequation418{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x8 G.* (G.inverse x8)) G.* x7) = (x9 G.* ((G.inverse x9) G.* x7)) => equation.group

\lemma grequation419{G : Group}(x0 x1 x2 x3 x4 : G): (x1 G.* (G.inverse x1)) = ((x1 G.* x3) G.* ((G.inverse x3) G.* (G.inverse x1))) => equation.group

\lemma grequation420{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x5 = x5 => equation.group

\lemma grequation421{G : Group}(x0 x1 x2 x3 : G): G.ide = (((x3 G.* x1) G.* x1) G.* ((x1 G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x1)))) G.* ((G.inverse x1) G.* ((G.inverse x1) G.* (G.inverse x3))))) => equation.group

\lemma grequation422{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (((x3 G.* (G.inverse x3)) G.* (x2 G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x2)))) G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation423{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x0 = x0 => equation.group

\lemma grequation424{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x7 G.* (G.inverse x7)) = (((x14 G.* x7) G.* ((x9 G.* x8) G.* ((G.inverse x8) G.* (G.inverse x9)))) G.* ((G.inverse x7) G.* (G.inverse x14))) => equation.group

\lemma grequation425{G : Group}(x0 x1 x2 : G): x0 = x0 => equation.group

\lemma grequation426{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x2 = (x2 G.* (x7 G.* (G.inverse x7))) => equation.group

\lemma grequation427{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x5 = x5 => equation.group

\lemma grequation428{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = ((x7 G.* ((x7 G.* (G.inverse x7)) G.* (G.inverse x7))) G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation429{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x5 G.* x3) G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x3)))) = x5 => equation.group

\lemma grequation430{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x1 = (((x4 G.* (G.inverse x4)) G.* x14) G.* ((x4 G.* (G.inverse x4)) G.* ((G.inverse x14) G.* x1))) => equation.group

\lemma grequation431{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x4 G.* (((G.inverse x4) G.* x1) G.* (G.inverse x1))) => equation.group

\lemma grequation432{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x6 G.* (G.inverse x6)) G.* (x8 G.* x9)) G.* ((G.inverse x9) G.* (G.inverse x8))) = (((x8 G.* ((G.inverse x8) G.* x5)) G.* (G.inverse x5)) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation433{G : Group}(x0 x1 : G): (((((x0 G.* x0) G.* x1) G.* (((G.inverse x1) G.* (G.inverse x0)) G.* (G.inverse x0))) G.* x1) G.* (x0 G.* ((G.inverse x0) G.* x0))) = (x1 G.* x0) => equation.group

\lemma grequation434{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x2 G.* x3) G.* (G.inverse x3)) = x2 => equation.group

\lemma grequation435{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((((x6 G.* (G.inverse x6)) G.* x1) G.* x2) G.* ((G.inverse x2) G.* x2)) = (x1 G.* x2) => equation.group

\lemma grequation436{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x0 G.* (G.inverse x0)) G.* x0) = x0 => equation.group

\lemma grequation437{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x6 G.* x0) G.* ((G.inverse x0) G.* (x3 G.* x8))) = ((((x6 G.* (x3 G.* x8)) G.* x8) G.* ((x0 G.* (G.inverse x0)) G.* (((G.inverse x8) G.* (((G.inverse x8) G.* x8) G.* x4)) G.* (G.inverse x4)))) G.* (x8 G.* (G.inverse x8))) => equation.group

\lemma grequation438{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation439{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* ((G.inverse x2) G.* ((x0 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x0))))) => equation.group

\lemma grequation440{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x10 G.* (G.inverse x10)) G.* x0) = x0 => equation.group

\lemma grequation441{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((((x2 G.* (G.inverse x2)) G.* x6) G.* (G.inverse x6)) G.* x9) G.* (((G.inverse x9) G.* x9) G.* (G.inverse x9))) => equation.group

\lemma grequation442{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((x9 G.* (G.inverse x9)) G.* (x14 G.* (G.inverse x14))) => equation.group

\lemma grequation443{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x2 G.* (x8 G.* x3)) G.* x1) G.* ((x6 G.* (x2 G.* x4)) G.* (x5 G.* x2))) = ((((x2 G.* x8) G.* x3) G.* (x1 G.* (x6 G.* x2))) G.* ((x4 G.* x5) G.* (x6 G.* ((G.inverse x6) G.* x2)))) => equation.group

\lemma grequation444{G : Group}(x0 x1 x2 x3 x4 : G): ((((x1 G.* (G.inverse x1)) G.* x1) G.* x0) G.* (((x3 G.* (G.inverse x3)) G.* x2) G.* (G.inverse x2))) = (x1 G.* x0) => equation.group

\lemma grequation445{G : Group}(x0 x1 : G): (x1 G.* ((x1 G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x1))) = x1 => equation.group

\lemma grequation446{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x14 = ((x11 G.* ((x11 G.* x2) G.* (G.inverse x2))) G.* (((G.inverse x11) G.* (G.inverse x11)) G.* x14)) => equation.group

\lemma grequation447{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x2 G.* (x9 G.* ((x4 G.* x8) G.* (G.inverse x8)))) = ((x2 G.* x9) G.* x4) => equation.group

\lemma grequation448{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation449{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation450{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((x2 G.* (G.inverse x2)) G.* x1) G.* x0) = (x1 G.* x0) => equation.group

\lemma grequation451{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation452{G : Group}(x0 x1 x2 x3 x4 : G): (x1 G.* (G.inverse x1)) = ((x2 G.* ((x4 G.* (G.inverse x4)) G.* x0)) G.* ((G.inverse x0) G.* (G.inverse x2))) => equation.group

\lemma grequation453{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x0 = (x0 G.* (((x8 G.* ((G.inverse x8) G.* (G.inverse x0))) G.* ((x0 G.* (G.inverse x0)) G.* (x8 G.* (G.inverse x8)))) G.* (x0 G.* (x6 G.* (G.inverse x6))))) => equation.group

\lemma grequation454{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x2 G.* x4) G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x4)))) = x2 => equation.group

\lemma grequation455{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x9 G.* (G.inverse x9)) G.* ((x6 G.* (G.inverse x6)) G.* (x9 G.* x6))) = (x9 G.* x6) => equation.group

\lemma grequation456{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x14 = (x3 G.* ((G.inverse x3) G.* x14)) => equation.group

\lemma grequation457{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation458{G : Group}(x0 x1 x2 : G): ((x2 G.* (G.inverse x2)) G.* ((x2 G.* (G.inverse x2)) G.* x2)) = ((x2 G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation459{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x6 G.* (((x12 G.* x8) G.* x2) G.* (x9 G.* ((G.inverse x9) G.* (G.inverse x2))))) G.* ((G.inverse x8) G.* (G.inverse x12))) = x6 => equation.group

\lemma grequation460{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x6 G.* x4) G.* ((x2 G.* x0) G.* ((x2 G.* x1) G.* ((G.inverse x1) G.* ((G.inverse x2) G.* (G.inverse x0)))))) = ((x6 G.* x4) G.* x2) => equation.group

\lemma grequation461{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x7 G.* (x9 G.* ((G.inverse x9) G.* (G.inverse x7)))) => equation.group

\lemma grequation462{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((((x2 G.* (G.inverse x2)) G.* x5) G.* (x4 G.* ((G.inverse x4) G.* x6))) G.* (x2 G.* x5)) = ((x5 G.* x6) G.* (x2 G.* x5)) => equation.group

\lemma grequation463{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x1 G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x1)))) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation464{G : Group}(x0 x1 x2 x3 : G): ((x2 G.* (G.inverse x2)) G.* x0) = (x0 G.* (x0 G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x0)))) => equation.group

\lemma grequation465{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x3 G.* (G.inverse x3)) G.* (x11 G.* (G.inverse x11))) G.* (x5 G.* x6)) = (x5 G.* x6) => equation.group

\lemma grequation466{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = ((x3 G.* x11) G.* ((G.inverse x11) G.* (G.inverse x3))) => equation.group

\lemma grequation467{G : Group}(x0 x1 : G): x0 = x0 => equation.group

\lemma grequation468{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x5 G.* x5) = (x5 G.* ((x5 G.* x4) G.* (G.inverse x4))) => equation.group

\lemma grequation469{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x1 G.* x5) = ((x1 G.* (x8 G.* x1)) G.* (((G.inverse x1) G.* (G.inverse x8)) G.* x5)) => equation.group

\lemma grequation470{G : Group}(x0 x1 x2 : G): (((x0 G.* x0) G.* x2) G.* (G.inverse x2)) = ((x0 G.* (x0 G.* x0)) G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x0))) => equation.group

\lemma grequation471{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x12 G.* ((G.inverse x12) G.* (x7 G.* (G.inverse x7)))) G.* x5) = ((x11 G.* (x4 G.* (G.inverse x4))) G.* ((G.inverse x11) G.* x5)) => equation.group

\lemma grequation472{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x9 G.* (G.inverse x9)) = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation473{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x5 G.* ((((G.inverse x5) G.* x9) G.* (G.inverse x9)) G.* (x8 G.* (G.inverse x8)))) => equation.group

\lemma grequation474{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = ((x2 G.* x5) G.* (((((x5 G.* x2) G.* (G.inverse x2)) G.* ((G.inverse x5) G.* (G.inverse x5))) G.* (((G.inverse x2) G.* x4) G.* (G.inverse x4))) G.* ((x3 G.* ((G.inverse x3) G.* x4)) G.* (x5 G.* ((G.inverse x5) G.* (G.inverse x4)))))) => equation.group

\lemma grequation475{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x3 G.* x2) = (x3 G.* x2) => equation.group

\lemma grequation476{G : Group}(x0 x1 x2 x3 : G): x0 = x0 => equation.group

\lemma grequation477{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (((x0 G.* x4) G.* (x2 G.* (x3 G.* x0))) G.* (((G.inverse x0) G.* ((G.inverse x3) G.* ((G.inverse x2) G.* (G.inverse x4)))) G.* (G.inverse x0))) => equation.group

\lemma grequation478{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation479{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x2 G.* (x7 G.* ((((G.inverse x7) G.* x0) G.* x7) G.* (x6 G.* (((G.inverse x6) G.* x5) G.* (((G.inverse x5) G.* (G.inverse x7)) G.* ((G.inverse x0) G.* (G.inverse x2)))))))) => equation.group

\lemma grequation480{G : Group}(x0 x1 x2 : G): (((x0 G.* (((G.inverse x0) G.* x1) G.* x0)) G.* ((((G.inverse x0) G.* (x2 G.* x0)) G.* x0) G.* ((x0 G.* (G.inverse x0)) G.* x2))) G.* ((x1 G.* x1) G.* (G.inverse x1))) = (((x1 G.* x2) G.* x0) G.* ((x0 G.* x2) G.* x1)) => equation.group

\lemma grequation481{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x7 G.* (x5 G.* (G.inverse x5))) = x7 => equation.group

\lemma grequation482{G : Group}(x0 x1 x2 x3 x4 x5 : G): x4 = ((x4 G.* x5) G.* (G.inverse x5)) => equation.group

\lemma grequation483{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (((x8 G.* (G.inverse x8)) G.* x7) G.* (((G.inverse x7) G.* x7) G.* (x7 G.* ((x5 G.* (G.inverse x5)) G.* (G.inverse x7))))) = x7 => equation.group

\lemma grequation484{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x1 G.* ((x6 G.* (x2 G.* (G.inverse x2))) G.* (G.inverse x6))) = x1 => equation.group

\lemma grequation485{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x8 G.* x0) = ((x13 G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x13))) G.* (x8 G.* x0)) => equation.group

\lemma grequation486{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation487{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x12 G.* x10) G.* (((G.inverse x10) G.* (x10 G.* (x3 G.* (G.inverse x3)))) G.* ((((G.inverse x10) G.* ((G.inverse x12) G.* x13)) G.* (G.inverse x13)) G.* (x10 G.* (G.inverse x10))))) = (x13 G.* (G.inverse x13)) => equation.group

\lemma grequation488{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x1 G.* ((x0 G.* (x1 G.* x5)) G.* (x1 G.* (x1 G.* x2)))) G.* ((((G.inverse x2) G.* ((G.inverse x1) G.* x5)) G.* (G.inverse x5)) G.* ((G.inverse x1) G.* (G.inverse x5)))) = ((x1 G.* x0) G.* x1) => equation.group

\lemma grequation489{G : Group}(x0 x1 x2 x3 x4 : G): (x4 G.* (((G.inverse x4) G.* x1) G.* x2)) = (x0 G.* ((x4 G.* (((G.inverse x4) G.* (G.inverse x0)) G.* ((x2 G.* (G.inverse x2)) G.* x2))) G.* (((G.inverse x2) G.* ((x1 G.* (G.inverse x1)) G.* x1)) G.* x2))) => equation.group

\lemma grequation490{G : Group}(x0 x1 x2 : G): (x2 G.* ((G.inverse x2) G.* x1)) = ((x1 G.* (x1 G.* x0)) G.* ((G.inverse x0) G.* (G.inverse x1))) => equation.group

\lemma grequation491{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x8 = x8 => equation.group

\lemma grequation492{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x8 = x8 => equation.group

\lemma grequation493{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x4 G.* x3) G.* (x6 G.* (G.inverse x6))) = (((((x3 G.* (x6 G.* x4)) G.* (x6 G.* (G.inverse x6))) G.* ((G.inverse x4) G.* (G.inverse x6))) G.* (G.inverse x3)) G.* (x4 G.* x3)) => equation.group

\lemma grequation494{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x5 G.* (G.inverse x5)) G.* x7) = ((x7 G.* x0) G.* (G.inverse x0)) => equation.group

\lemma grequation495{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x2 = x2 => equation.group

\lemma grequation496{G : Group}(x0 x1 x2 : G): x1 = x1 => equation.group

\lemma grequation497{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((((x3 G.* ((G.inverse x3) G.* (x3 G.* x0))) G.* x6) G.* ((x1 G.* x3) G.* (G.inverse x3))) G.* (x3 G.* (((x4 G.* (G.inverse x4)) G.* (G.inverse x3)) G.* ((G.inverse x1) G.* (G.inverse x6))))) = (x3 G.* x0) => equation.group

\lemma grequation498{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x9 = ((x9 G.* x9) G.* (G.inverse x9)) => equation.group

\lemma grequation499{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x1 G.* (G.inverse x1)) = ((x1 G.* x0) G.* (x4 G.* (((G.inverse x4) G.* (G.inverse x0)) G.* (G.inverse x1)))) => equation.group

\lemma grequation500{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation501{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x8 G.* x6) = (((x8 G.* x2) G.* (((x10 G.* (G.inverse x10)) G.* (G.inverse x2)) G.* (x8 G.* (G.inverse x8)))) G.* ((((G.inverse x8) G.* x8) G.* x1) G.* (((G.inverse x1) G.* x6) G.* (x2 G.* (G.inverse x2))))) => equation.group

\lemma grequation502{G : Group}(x0 x1 x2 x3 x4 : G): (((x4 G.* x2) G.* x1) G.* (G.inverse x1)) = (x4 G.* (x2 G.* ((((G.inverse x2) G.* x2) G.* x2) G.* (((G.inverse x2) G.* (G.inverse x2)) G.* x2)))) => equation.group

\lemma grequation503{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = ((x5 G.* (G.inverse x5)) G.* (x6 G.* (G.inverse x6))) => equation.group

\lemma grequation504{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation505{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* (x1 G.* (x4 G.* (G.inverse x4)))) = (x0 G.* x1) => equation.group

\lemma grequation506{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x11 = x11 => equation.group

\lemma grequation507{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation508{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x2 = x2 => equation.group

\lemma grequation509{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x9 G.* x0) G.* (G.inverse x0)) = (((((x5 G.* (G.inverse x5)) G.* x8) G.* ((G.inverse x8) G.* x8)) G.* (((((G.inverse x8) G.* x9) G.* x7) G.* x0) G.* ((((G.inverse x0) G.* x2) G.* (G.inverse x2)) G.* (G.inverse x7)))) G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation510{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x4 G.* (G.inverse x4)) G.* (x4 G.* (G.inverse x4))) G.* ((x4 G.* x2) G.* ((G.inverse x2) G.* (x5 G.* (G.inverse x5))))) = (x3 G.* ((G.inverse x3) G.* x4)) => equation.group

\lemma grequation511{G : Group}(x0 x1 x2 : G): (x1 G.* ((G.inverse x1) G.* x1)) = x1 => equation.group

\lemma grequation512{G : Group}(x0 x1 x2 x3 x4 : G): x0 = ((x3 G.* (x4 G.* (x0 G.* (x3 G.* x1)))) G.* (((G.inverse x1) G.* ((G.inverse x3) G.* (x4 G.* (G.inverse x4)))) G.* (((G.inverse x0) G.* ((G.inverse x4) G.* (G.inverse x3))) G.* x0))) => equation.group

\lemma grequation513{G : Group}(x0 x1 x2 x3 : G): G.ide = (x3 G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x3))) => equation.group

\lemma grequation514{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x7 = x7 => equation.group

\lemma grequation515{G : Group}(x0 x1 x2 x3 x4 x5 : G): x0 = x0 => equation.group

\lemma grequation516{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x7 = (((x7 G.* (x2 G.* x11)) G.* (x11 G.* (G.inverse x11))) G.* ((G.inverse x11) G.* (G.inverse x2))) => equation.group

\lemma grequation517{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x11 G.* ((G.inverse x11) G.* (x8 G.* x1))) = ((((x8 G.* x1) G.* x4) G.* x1) G.* ((G.inverse x1) G.* (G.inverse x4))) => equation.group

\lemma grequation518{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* ((x3 G.* x1) G.* x4)) = (x0 G.* (x3 G.* (x1 G.* x4))) => equation.group

\lemma grequation519{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x2 G.* ((G.inverse x2) G.* (x4 G.* x2))) G.* (x5 G.* (x10 G.* (G.inverse x10)))) G.* (G.inverse x5)) = (x4 G.* ((x0 G.* (G.inverse x0)) G.* x2)) => equation.group

\lemma grequation520{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation521{G : Group}(x0 x1 : G): x0 = x0 => equation.group

\lemma grequation522{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x2 G.* (G.inverse x2)) G.* x6) G.* x2) = (x6 G.* x2) => equation.group

\lemma grequation523{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((((((x4 G.* x2) G.* (G.inverse x2)) G.* (G.inverse x4)) G.* (x2 G.* ((x6 G.* (x0 G.* (G.inverse x0))) G.* ((G.inverse x6) G.* (G.inverse x2))))) G.* (x2 G.* (x6 G.* (x3 G.* (G.inverse x3))))) G.* ((G.inverse x6) G.* x1)) = (x2 G.* x1) => equation.group

\lemma grequation524{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x5 G.* ((G.inverse x5) G.* x3)) = ((x0 G.* (G.inverse x0)) G.* (x3 G.* (x2 G.* (G.inverse x2)))) => equation.group

\lemma grequation525{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x2 G.* (((x9 G.* x6) G.* (G.inverse x6)) G.* ((G.inverse x9) G.* (G.inverse x2)))) => equation.group

\lemma grequation526{G : Group}(x0 x1 x2 x3 x4 : G): x0 = x0 => equation.group

\lemma grequation527{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x5 G.* ((G.inverse x5) G.* (x1 G.* ((G.inverse x1) G.* x5)))) = x5 => equation.group

\lemma grequation528{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x10 = x10 => equation.group

\lemma grequation529{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation530{G : Group}(x0 x1 x2 x3 : G): (((x3 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x3) G.* (x2 G.* ((G.inverse x2) G.* x1)))) = (((x3 G.* x2) G.* (G.inverse x2)) G.* (x1 G.* ((G.inverse x1) G.* (((G.inverse x3) G.* x1) G.* (x2 G.* (G.inverse x2)))))) => equation.group

\lemma grequation531{G : Group}(x0 x1 : G): x0 = ((x1 G.* (G.inverse x1)) G.* x0) => equation.group

\lemma grequation532{G : Group}(x0 x1 x2 : G): (((x2 G.* ((x0 G.* x2) G.* (x2 G.* (G.inverse x2)))) G.* ((G.inverse x2) G.* (G.inverse x0))) G.* (G.inverse x2)) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation533{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x10 G.* x0) = ((x10 G.* x5) G.* ((G.inverse x5) G.* x0)) => equation.group

\lemma grequation534{G : Group}(x0 x1 x2 x3 x4 : G): ((x4 G.* x0) G.* (G.inverse x0)) = x4 => equation.group

\lemma grequation535{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x3 = (((((x12 G.* (G.inverse x12)) G.* x14) G.* (x9 G.* ((G.inverse x9) G.* (G.inverse x14)))) G.* (x14 G.* (G.inverse x14))) G.* (x10 G.* ((G.inverse x10) G.* x3))) => equation.group

\lemma grequation536{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x4 G.* x7) G.* ((G.inverse x7) G.* ((G.inverse x4) G.* x10))) = (x10 G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation537{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x3 G.* ((((G.inverse x3) G.* x5) G.* (G.inverse x5)) G.* (x0 G.* (G.inverse x0)))) G.* ((x5 G.* (G.inverse x5)) G.* x3)) = (x3 G.* (x7 G.* (G.inverse x7))) => equation.group

\lemma grequation538{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((((x7 G.* (x6 G.* x2)) G.* ((G.inverse x2) G.* (G.inverse x6))) G.* (G.inverse x7)) G.* x8) = (((x8 G.* x1) G.* (x3 G.* (G.inverse x3))) G.* ((x8 G.* (G.inverse x8)) G.* (G.inverse x1))) => equation.group

\lemma grequation539{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x5 G.* ((((G.inverse x5) G.* x6) G.* ((G.inverse x6) G.* x1)) G.* (G.inverse x1))) => equation.group

\lemma grequation540{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x4 G.* x6) G.* ((G.inverse x6) G.* x1)) = (x4 G.* ((x4 G.* (G.inverse x4)) G.* x1)) => equation.group

\lemma grequation541{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation542{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x1 G.* ((G.inverse x1) G.* x2)) = ((x2 G.* x6) G.* (G.inverse x6)) => equation.group

\lemma grequation543{G : Group}(x0 x1 : G): ((x1 G.* x1) G.* ((G.inverse x1) G.* x0)) = (x1 G.* x0) => equation.group

\lemma grequation544{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((((x3 G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x3)) G.* x0) G.* (x4 G.* x0)) = ((x0 G.* x5) G.* ((x1 G.* x3) G.* (((G.inverse x3) G.* ((G.inverse x1) G.* ((G.inverse x5) G.* x4))) G.* x0))) => equation.group

\lemma grequation545{G : Group}(x0 x1 : G): G.ide = (((x1 G.* x1) G.* (G.inverse x1)) G.* (G.inverse x1)) => equation.group

\lemma grequation546{G : Group}(x0 x1 x2 x3 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation547{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (((x2 G.* x2) G.* (G.inverse x2)) G.* x5) = ((x2 G.* x5) G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation548{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((((x3 G.* (G.inverse x3)) G.* (x1 G.* (x1 G.* x0))) G.* ((G.inverse x0) G.* (((G.inverse x1) G.* ((x1 G.* x3) G.* (G.inverse x3))) G.* (G.inverse x1)))) G.* (((G.inverse x1) G.* (x1 G.* (G.inverse x1))) G.* x1)) = x1 => equation.group

\lemma grequation549{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x9 = (x4 G.* ((G.inverse x4) G.* x9)) => equation.group

\lemma grequation550{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x3 G.* (x4 G.* (x3 G.* (G.inverse x3)))) G.* (G.inverse x4)) G.* ((G.inverse x3) G.* x6)) = x6 => equation.group

\lemma grequation551{G : Group}(x0 x1 x2 x3 x4 : G): (x1 G.* ((G.inverse x1) G.* x3)) = ((x1 G.* (G.inverse x1)) G.* x3) => equation.group

\lemma grequation552{G : Group}(x0 x1 : G): (x0 G.* ((G.inverse x0) G.* x1)) = x1 => equation.group

\lemma grequation553{G : Group}(x0 x1 x2 x3 : G): G.ide = (((x3 G.* x1) G.* (x2 G.* (G.inverse x2))) G.* ((G.inverse x1) G.* (G.inverse x3))) => equation.group

\lemma grequation554{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x0 = x0 => equation.group

\lemma grequation555{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation556{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x5 G.* x9) = ((x5 G.* ((x6 G.* (G.inverse x6)) G.* x1)) G.* ((((G.inverse x1) G.* x4) G.* ((G.inverse x4) G.* x9)) G.* (x1 G.* (G.inverse x1)))) => equation.group

\lemma grequation557{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x1 G.* x2) G.* (((x0 G.* (G.inverse x0)) G.* (G.inverse x2)) G.* ((((x2 G.* (G.inverse x2)) G.* x3) G.* (G.inverse x3)) G.* (G.inverse x1)))) => equation.group

\lemma grequation558{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x9 G.* ((G.inverse x9) G.* x13)) = x13 => equation.group

\lemma grequation559{G : Group}(x0 x1 x2 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation560{G : Group}(x0 x1 x2 : G): x1 = ((x1 G.* (G.inverse x1)) G.* x1) => equation.group

\lemma grequation561{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = ((x9 G.* (x5 G.* (G.inverse x5))) G.* (G.inverse x9)) => equation.group

\lemma grequation562{G : Group}(x0 x1 x2 : G): ((x2 G.* (G.inverse x2)) G.* x1) = x1 => equation.group

\lemma grequation563{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x6 = x6 => equation.group

\lemma grequation564{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((((x1 G.* ((G.inverse x1) G.* x0)) G.* (x8 G.* (G.inverse x8))) G.* x0) G.* (x5 G.* (G.inverse x5))) = (x0 G.* x0) => equation.group

\lemma grequation565{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x12 G.* x11) = (x12 G.* x11) => equation.group

\lemma grequation566{G : Group}(x0 x1 : G): (x0 G.* x0) = (((x0 G.* x1) G.* (((x1 G.* (G.inverse x1)) G.* (x1 G.* (G.inverse x1))) G.* (x1 G.* (G.inverse x1)))) G.* ((G.inverse x1) G.* x0)) => equation.group

\lemma grequation567{G : Group}(x0 x1 : G): ((x0 G.* x0) G.* (G.inverse x0)) = x0 => equation.group

\lemma grequation568{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x2 = x2 => equation.group

\lemma grequation569{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x4 G.* (((G.inverse x4) G.* (x7 G.* x3)) G.* ((x3 G.* ((G.inverse x3) G.* x4)) G.* (G.inverse x4)))) G.* (G.inverse x3)) = x7 => equation.group

\lemma grequation570{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x7 G.* ((G.inverse x7) G.* x10)) = (((((x7 G.* x11) G.* (x11 G.* (G.inverse x11))) G.* (G.inverse x11)) G.* (G.inverse x7)) G.* x10) => equation.group

\lemma grequation571{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x11 G.* (G.inverse x11)) G.* x12) = x12 => equation.group

\lemma grequation572{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x2 G.* (((G.inverse x2) G.* x1) G.* (x5 G.* (x2 G.* (G.inverse x2))))) G.* x5) = (x1 G.* (((x5 G.* x0) G.* ((x6 G.* x3) G.* (x4 G.* (G.inverse x4)))) G.* ((G.inverse x3) G.* ((((G.inverse x6) G.* (x5 G.* (G.inverse x5))) G.* (G.inverse x0)) G.* x5)))) => equation.group

\lemma grequation573{G : Group}(x0 x1 x2 x3 x4 : G): ((x1 G.* (G.inverse x1)) G.* x0) = ((x0 G.* ((x4 G.* x0) G.* (x2 G.* (G.inverse x2)))) G.* ((G.inverse x0) G.* (G.inverse x4))) => equation.group

\lemma grequation574{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x2 G.* x6) G.* (((x1 G.* x0) G.* ((G.inverse x0) G.* (x7 G.* x9))) G.* (((G.inverse x9) G.* (G.inverse x7)) G.* ((G.inverse x1) G.* (G.inverse x6))))) = x2 => equation.group

\lemma grequation575{G : Group}(x0 x1 : G): (x1 G.* (G.inverse x1)) = (((x1 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x1))) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation576{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((x8 G.* ((G.inverse x8) G.* x5)) G.* (G.inverse x5)) G.* ((x14 G.* x2) G.* (G.inverse x2))) = ((x12 G.* (G.inverse x12)) G.* (x8 G.* ((G.inverse x8) G.* x14))) => equation.group

\lemma grequation577{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = ((((x1 G.* x6) G.* (G.inverse x6)) G.* (G.inverse x1)) G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation578{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation579{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x2 G.* (G.inverse x2)) G.* x1) = (x1 G.* (x7 G.* (G.inverse x7))) => equation.group

\lemma grequation580{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((((x5 G.* (G.inverse x5)) G.* (x8 G.* x2)) G.* (x7 G.* (G.inverse x7))) G.* ((G.inverse x2) G.* (x5 G.* x2))) = (x8 G.* (x5 G.* x2)) => equation.group

\lemma grequation581{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x11 = x11 => equation.group

\lemma grequation582{G : Group}(x0 x1 x2 : G): G.ide = (((((x1 G.* (G.inverse x1)) G.* x2) G.* ((G.inverse x2) G.* (x1 G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x1)))))) G.* (x2 G.* (G.inverse x2))) G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation583{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x8 = x8 => equation.group

\lemma grequation584{G : Group}(x0 x1 x2 x3 : G): (x3 G.* (x3 G.* x3)) = (((x3 G.* (x3 G.* x3)) G.* (x0 G.* ((G.inverse x0) G.* x2))) G.* (G.inverse x2)) => equation.group

\lemma grequation585{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x3 G.* ((G.inverse x3) G.* x3)) = x3 => equation.group

\lemma grequation586{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation587{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x13 G.* (G.inverse x13)) => equation.group

\lemma grequation588{G : Group}(x0 x1 : G): (x1 G.* x0) = (x1 G.* x0) => equation.group

\lemma grequation589{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x4 G.* (G.inverse x4)) G.* x1) = x1 => equation.group

\lemma grequation590{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x11 G.* (G.inverse x11)) = ((x4 G.* x6) G.* ((G.inverse x6) G.* (G.inverse x4))) => equation.group

\lemma grequation591{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x1 G.* (x1 G.* ((G.inverse x1) G.* ((G.inverse x1) G.* x1)))) = x1 => equation.group

\lemma grequation592{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x3 G.* ((G.inverse x3) G.* x3)) = (((((x8 G.* x8) G.* (x8 G.* (G.inverse x8))) G.* (G.inverse x8)) G.* ((G.inverse x8) G.* (x9 G.* ((G.inverse x9) G.* x0)))) G.* ((((x5 G.* x7) G.* ((G.inverse x7) G.* (G.inverse x5))) G.* (G.inverse x0)) G.* x3)) => equation.group

\lemma grequation593{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x9 = x9 => equation.group

\lemma grequation594{G : Group}(x0 x1 : G): G.ide = (((x0 G.* x0) G.* ((x1 G.* x0) G.* (G.inverse x0))) G.* (((x1 G.* (G.inverse x1)) G.* (G.inverse x1)) G.* ((G.inverse x0) G.* ((((x0 G.* x1) G.* (G.inverse x1)) G.* (x0 G.* (G.inverse x0))) G.* ((G.inverse x0) G.* (G.inverse x0)))))) => equation.group

\lemma grequation595{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x5 G.* (G.inverse x5)) G.* (x1 G.* (G.inverse x1))) = (x5 G.* ((x3 G.* (G.inverse x3)) G.* (G.inverse x5))) => equation.group

\lemma grequation596{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x8 G.* x10) G.* (x10 G.* (G.inverse x10))) = (x8 G.* x10) => equation.group

\lemma grequation597{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x6 = x6 => equation.group

\lemma grequation598{G : Group}(x0 x1 x2 x3 x4 : G): ((x0 G.* x0) G.* (x2 G.* (G.inverse x2))) = (x0 G.* x0) => equation.group

\lemma grequation599{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation600{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = ((x7 G.* (G.inverse x7)) G.* (x6 G.* (G.inverse x6))) => equation.group

\lemma grequation601{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x8 = x8 => equation.group

\lemma grequation602{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* (((G.inverse x0) G.* x1) G.* x4)) = (x1 G.* x4) => equation.group

\lemma grequation603{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation604{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((x5 G.* (G.inverse x5)) G.* (x14 G.* (G.inverse x14))) => equation.group

\lemma grequation605{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x1 G.* (x4 G.* (G.inverse x4))) = x1 => equation.group

\lemma grequation606{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x7 = x7 => equation.group

\lemma grequation607{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (((x1 G.* ((x13 G.* x6) G.* (G.inverse x6))) G.* ((x11 G.* x12) G.* (G.inverse x12))) G.* (x7 G.* (((G.inverse x7) G.* ((G.inverse x11) G.* (G.inverse x13))) G.* ((((x13 G.* ((G.inverse x13) G.* (G.inverse x1))) G.* x2) G.* ((G.inverse x2) G.* x2)) G.* (G.inverse x2))))) => equation.group

\lemma grequation608{G : Group}(x0 x1 : G): (x1 G.* x0) = (x1 G.* x0) => equation.group

\lemma grequation609{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x4 G.* (G.inverse x4)) G.* (((x5 G.* (G.inverse x5)) G.* x3) G.* (G.inverse x3))) = (((x2 G.* x2) G.* ((((G.inverse x2) G.* (G.inverse x2)) G.* (x4 G.* ((G.inverse x4) G.* x3))) G.* (x4 G.* (G.inverse x4)))) G.* (G.inverse x3)) => equation.group

\lemma grequation610{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation611{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x8 G.* x6) = ((x8 G.* ((x4 G.* (G.inverse x4)) G.* x4)) G.* ((G.inverse x4) G.* x6)) => equation.group

\lemma grequation612{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x10 G.* (G.inverse x10)) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation613{G : Group}(x0 x1 x2 : G): ((x2 G.* x0) G.* (G.inverse x0)) = ((x2 G.* (G.inverse x2)) G.* x2) => equation.group

\lemma grequation614{G : Group}(x0 x1 x2 x3 : G): G.ide = ((x0 G.* (x2 G.* (G.inverse x2))) G.* (((G.inverse x0) G.* x1) G.* (G.inverse x1))) => equation.group

\lemma grequation615{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x0 G.* (x0 G.* (G.inverse x0))) = x0 => equation.group

\lemma grequation616{G : Group}(x0 x1 x2 x3 : G): x1 = x1 => equation.group

\lemma grequation617{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation618{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x13 G.* (G.inverse x13)) = (((x8 G.* x2) G.* (((G.inverse x2) G.* (G.inverse x8)) G.* (x10 G.* x0))) G.* ((G.inverse x0) G.* (G.inverse x10))) => equation.group

\lemma grequation619{G : Group}(x0 x1 x2 x3 x4 x5 : G): x4 = x4 => equation.group

\lemma grequation620{G : Group}(x0 x1 x2 x3 : G): x1 = x1 => equation.group

\lemma grequation621{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x0 G.* x5) G.* x3) = (x0 G.* (x5 G.* x3)) => equation.group

\lemma grequation622{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x5 G.* (G.inverse x5)) G.* x3) = x3 => equation.group

\lemma grequation623{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x2 G.* x2) = (x2 G.* x2) => equation.group

\lemma grequation624{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = ((x2 G.* ((x1 G.* (x2 G.* x1)) G.* ((x3 G.* ((G.inverse x3) G.* x4)) G.* (G.inverse x4)))) G.* (((G.inverse x1) G.* ((G.inverse x2) G.* (((G.inverse x1) G.* x2) G.* ((G.inverse x2) G.* (G.inverse x2))))) G.* (x5 G.* (G.inverse x5)))) => equation.group

\lemma grequation625{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x4 G.* (G.inverse x4)) G.* x0) G.* (((G.inverse x0) G.* x6) G.* ((G.inverse x6) G.* x2))) = (x2 G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation626{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (((G.inverse x2) G.* x1) G.* (G.inverse x1))) => equation.group

\lemma grequation627{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x0 G.* x8) G.* (G.inverse x8)) = x0 => equation.group

\lemma grequation628{G : Group}(x0 x1 : G): ((((x1 G.* (G.inverse x1)) G.* x0) G.* ((G.inverse x0) G.* x0)) G.* (((G.inverse x0) G.* (x0 G.* x1)) G.* (G.inverse x1))) = ((x0 G.* x0) G.* (G.inverse x0)) => equation.group

\lemma grequation629{G : Group}(x0 x1 x2 : G): (x1 G.* (x1 G.* ((G.inverse x1) G.* (G.inverse x1)))) = (x2 G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x2)))) => equation.group

\lemma grequation630{G : Group}(x0 x1 x2 x3 x4 : G): ((x0 G.* (G.inverse x0)) G.* (x2 G.* (G.inverse x2))) = ((x2 G.* (((x1 G.* x1) G.* (G.inverse x1)) G.* ((((G.inverse x1) G.* (G.inverse x2)) G.* x4) G.* (G.inverse x4)))) G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation631{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((((x5 G.* (G.inverse x5)) G.* (x7 G.* (G.inverse x7))) G.* x12) G.* x12) = ((x12 G.* x12) G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation632{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x4 G.* ((G.inverse x4) G.* x10)) G.* x5) = ((x10 G.* x5) G.* ((x14 G.* (G.inverse x14)) G.* ((G.inverse x5) G.* x5))) => equation.group

\lemma grequation633{G : Group}(x0 x1 x2 x3 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation634{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((x2 G.* (x13 G.* x14)) G.* (G.inverse x14)) G.* ((G.inverse x13) G.* (x8 G.* (x14 G.* ((G.inverse x14) G.* (G.inverse x8)))))) = x2 => equation.group

\lemma grequation635{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x0 G.* (x8 G.* (x4 G.* (G.inverse x4)))) = (((x0 G.* x8) G.* x6) G.* (G.inverse x6)) => equation.group

\lemma grequation636{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x0 G.* x5) G.* (x1 G.* x1)) = ((((x4 G.* (G.inverse x4)) G.* (x0 G.* (x5 G.* (x1 G.* x0)))) G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x0)))) G.* ((x1 G.* x1) G.* (G.inverse x1))) => equation.group

\lemma grequation637{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x12 G.* (G.inverse x12)) => equation.group

\lemma grequation638{G : Group}(x0 x1 x2 : G): x0 = x0 => equation.group

\lemma grequation639{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x5 = ((x5 G.* (G.inverse x5)) G.* x5) => equation.group

\lemma grequation640{G : Group}(x0 x1 : G): ((x0 G.* (G.inverse x0)) G.* (((x0 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x0))) = (x0 G.* ((G.inverse x0) G.* ((x0 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x0))))) => equation.group

\lemma grequation641{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x8 G.* (((G.inverse x8) G.* x2) G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x2))))) => equation.group

\lemma grequation642{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (((x8 G.* x6) G.* (((x0 G.* (x5 G.* (G.inverse x5))) G.* (G.inverse x0)) G.* x0)) G.* ((G.inverse x0) G.* ((G.inverse x6) G.* (G.inverse x8)))) => equation.group

\lemma grequation643{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (((x2 G.* (G.inverse x2)) G.* x8) G.* (G.inverse x8)) => equation.group

\lemma grequation644{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x8 G.* (G.inverse x8)) G.* x5) = (x5 G.* (((x6 G.* (x2 G.* x5)) G.* ((((G.inverse x5) G.* x8) G.* (G.inverse x8)) G.* (x6 G.* (G.inverse x6)))) G.* (((x4 G.* (G.inverse x4)) G.* (G.inverse x2)) G.* (G.inverse x6)))) => equation.group

\lemma grequation645{G : Group}(x0 x1 x2 x3 : G): ((x2 G.* (G.inverse x2)) G.* (x0 G.* x3)) = (((x0 G.* (G.inverse x0)) G.* x0) G.* x3) => equation.group

\lemma grequation646{G : Group}(x0 x1 x2 : G): G.ide = (((x2 G.* (((G.inverse x2) G.* x1) G.* x1)) G.* (x1 G.* x2)) G.* (((G.inverse x2) G.* (G.inverse x1)) G.* ((G.inverse x1) G.* (G.inverse x1)))) => equation.group

\lemma grequation647{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = ((x9 G.* (x8 G.* (G.inverse x8))) G.* (G.inverse x9)) => equation.group

\lemma grequation648{G : Group}(x0 x1 x2 : G): G.ide = (((x2 G.* ((x0 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x0)))) G.* x2) G.* ((x2 G.* (G.inverse x2)) G.* ((G.inverse x2) G.* (G.inverse x2)))) => equation.group

\lemma grequation649{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* (x4 G.* ((G.inverse x4) G.* x3))) = (x3 G.* (((G.inverse x3) G.* x0) G.* x3)) => equation.group

\lemma grequation650{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x7 = x7 => equation.group

\lemma grequation651{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x9 G.* (x1 G.* (G.inverse x1))) = x9 => equation.group

\lemma grequation652{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x0 G.* x5) G.* (G.inverse x5)) G.* ((x3 G.* x0) G.* (G.inverse x0))) = (x0 G.* x3) => equation.group

\lemma grequation653{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x7 = ((x1 G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x1)))) G.* (x0 G.* ((G.inverse x0) G.* x7))) => equation.group

\lemma grequation654{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x6 G.* (((G.inverse x6) G.* x1) G.* (((G.inverse x1) G.* ((x1 G.* x2) G.* ((G.inverse x2) G.* x6))) G.* (((((G.inverse x6) G.* x0) G.* ((G.inverse x0) G.* x2)) G.* (x7 G.* x7)) G.* (((G.inverse x7) G.* (G.inverse x7)) G.* (G.inverse x2)))))) = (x5 G.* ((G.inverse x5) G.* x1)) => equation.group

\lemma grequation655{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x10 G.* (G.inverse x10)) G.* (x9 G.* x0)) = (x9 G.* x0) => equation.group

\lemma grequation656{G : Group}(x0 x1 x2 x3 : G): (((x0 G.* (G.inverse x0)) G.* x1) G.* ((G.inverse x1) G.* x1)) = (((x1 G.* x0) G.* x0) G.* ((G.inverse x0) G.* (G.inverse x0))) => equation.group

\lemma grequation657{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x6 = ((x6 G.* x6) G.* (G.inverse x6)) => equation.group

\lemma grequation658{G : Group}(x0 x1 x2 x3 x4 : G): x4 = (x4 G.* (((x1 G.* x4) G.* (G.inverse x4)) G.* (G.inverse x1))) => equation.group

\lemma grequation659{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation660{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((x2 G.* x7) G.* (G.inverse x7)) G.* (G.inverse x2)) => equation.group

\lemma grequation661{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x8 G.* x0) = (x8 G.* x0) => equation.group

\lemma grequation662{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x2 G.* (G.inverse x2)) = (((x5 G.* (G.inverse x5)) G.* x7) G.* (G.inverse x7)) => equation.group

\lemma grequation663{G : Group}(x0 x1 x2 x3 : G): x0 = x0 => equation.group

\lemma grequation664{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x11 G.* ((((G.inverse x11) G.* x5) G.* ((G.inverse x5) G.* (x9 G.* (G.inverse x9)))) G.* (x10 G.* ((G.inverse x10) G.* x8)))) = x8 => equation.group

\lemma grequation665{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x9 G.* x2) G.* (((G.inverse x2) G.* (x11 G.* (G.inverse x11))) G.* (G.inverse x9))) = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation666{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x13 G.* ((G.inverse x13) G.* x8)) = (((x9 G.* x5) G.* (x13 G.* (x3 G.* x7))) G.* ((G.inverse x7) G.* ((((G.inverse x3) G.* (((G.inverse x13) G.* (G.inverse x5)) G.* (G.inverse x9))) G.* x11) G.* ((G.inverse x11) G.* (x2 G.* ((G.inverse x2) G.* x8)))))) => equation.group

\lemma grequation667{G : Group}(x0 x1 x2 x3 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation668{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation669{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x1 = x1 => equation.group

\lemma grequation670{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation671{G : Group}(x0 x1 x2 x3 : G): x0 = (x0 G.* (x0 G.* ((x2 G.* x2) G.* (((G.inverse x2) G.* (G.inverse x2)) G.* (G.inverse x0))))) => equation.group

\lemma grequation672{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (((((x3 G.* x2) G.* (((G.inverse x2) G.* x4) G.* (G.inverse x4))) G.* x4) G.* (((((x2 G.* x2) G.* (G.inverse x2)) G.* ((G.inverse x2) G.* (G.inverse x4))) G.* ((G.inverse x3) G.* x4)) G.* (G.inverse x4))) G.* ((x2 G.* (G.inverse x2)) G.* x5)) = x5 => equation.group

\lemma grequation673{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x4 G.* (G.inverse x4)) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation674{G : Group}(x0 x1 x2 x3 : G): x0 = x0 => equation.group

\lemma grequation675{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation676{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x2 = x2 => equation.group

\lemma grequation677{G : Group}(x0 x1 : G): x1 = (((x1 G.* (G.inverse x1)) G.* x1) G.* ((x0 G.* ((G.inverse x0) G.* x0)) G.* (G.inverse x0))) => equation.group

\lemma grequation678{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x0 G.* ((((x7 G.* x9) G.* (G.inverse x9)) G.* ((G.inverse x7) G.* x9)) G.* x4)) = ((x0 G.* x9) G.* ((x4 G.* x3) G.* (G.inverse x3))) => equation.group

\lemma grequation679{G : Group}(x0 x1 x2 x3 : G): G.ide = ((((x1 G.* x0) G.* ((G.inverse x0) G.* (x3 G.* x1))) G.* ((G.inverse x1) G.* (G.inverse x3))) G.* (G.inverse x1)) => equation.group

\lemma grequation680{G : Group}(x0 x1 x2 x3 x4 : G): x0 = (x4 G.* ((G.inverse x4) G.* x0)) => equation.group

\lemma grequation681{G : Group}(x0 x1 x2 : G): x1 = ((x2 G.* (G.inverse x2)) G.* x1) => equation.group

\lemma grequation682{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x3 G.* x4) = (x3 G.* x4) => equation.group

\lemma grequation683{G : Group}(x0 x1 x2 x3 x4 : G): x1 = x1 => equation.group

\lemma grequation684{G : Group}(x0 x1 x2 : G): (x1 G.* (G.inverse x1)) = (x1 G.* (((G.inverse x1) G.* x0) G.* (G.inverse x0))) => equation.group

\lemma grequation685{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x2 G.* ((x1 G.* x14) G.* (x11 G.* (G.inverse x11)))) = (x2 G.* (((x1 G.* (x14 G.* x3)) G.* x10) G.* ((G.inverse x10) G.* (G.inverse x3)))) => equation.group

\lemma grequation686{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x1 = x1 => equation.group

\lemma grequation687{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x7 G.* ((G.inverse x7) G.* (x5 G.* x1))) G.* x4) = ((x5 G.* x1) G.* x4) => equation.group

\lemma grequation688{G : Group}(x0 x1 x2 x3 : G): x2 = x2 => equation.group

\lemma grequation689{G : Group}(x0 x1 x2 x3 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation690{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation691{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x2 G.* ((G.inverse x2) G.* (((x7 G.* x0) G.* (x8 G.* (G.inverse x8))) G.* (x3 G.* x2)))) = (x7 G.* ((x0 G.* x3) G.* x2)) => equation.group

\lemma grequation692{G : Group}(x0 x1 x2 x3 x4 : G): x2 = x2 => equation.group

\lemma grequation693{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x1 = (x1 G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation694{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x2 = ((x4 G.* (G.inverse x4)) G.* (x6 G.* ((G.inverse x6) G.* x2))) => equation.group

\lemma grequation695{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x7 G.* (((G.inverse x7) G.* x2) G.* (G.inverse x2))) => equation.group

\lemma grequation696{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((x8 G.* ((G.inverse x8) G.* (x11 G.* x8))) G.* (((x2 G.* (G.inverse x2)) G.* x7) G.* (x5 G.* ((G.inverse x5) G.* x8)))) G.* ((x5 G.* x10) G.* (((G.inverse x10) G.* ((G.inverse x5) G.* ((G.inverse x8) G.* (G.inverse x7)))) G.* (G.inverse x8)))) = x11 => equation.group

\lemma grequation697{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x2 = ((x2 G.* x0) G.* (G.inverse x0)) => equation.group

\lemma grequation698{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x8 = x8 => equation.group

\lemma grequation699{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation700{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (((x6 G.* (G.inverse x6)) G.* (x1 G.* (G.inverse x1))) G.* (x6 G.* (G.inverse x6))) => equation.group

\lemma grequation701{G : Group}(x0 x1 : G): x0 = (x0 G.* ((G.inverse x0) G.* x0)) => equation.group

\lemma grequation702{G : Group}(x0 x1 x2 x3 x4 : G): ((x4 G.* x2) G.* (G.inverse x2)) = ((x4 G.* (G.inverse x4)) G.* ((x4 G.* x0) G.* (G.inverse x0))) => equation.group

\lemma grequation703{G : Group}(x0 x1 : G): x1 = ((x1 G.* (G.inverse x1)) G.* x1) => equation.group

\lemma grequation704{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((((x0 G.* (x1 G.* x1)) G.* ((G.inverse x1) G.* (G.inverse x1))) G.* (G.inverse x0)) G.* (x3 G.* (x2 G.* (G.inverse x2)))) = (x3 G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation705{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* ((G.inverse x0) G.* (x3 G.* (x2 G.* x2)))) G.* ((((G.inverse x2) G.* (G.inverse x2)) G.* (G.inverse x3)) G.* (((x1 G.* (G.inverse x1)) G.* x0) G.* ((G.inverse x0) G.* x3)))) = x3 => equation.group

\lemma grequation706{G : Group}(x0 x1 x2 x3 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation707{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x3 = x3 => equation.group

\lemma grequation708{G : Group}(x0 x1 x2 : G): (x0 G.* x1) = ((((x1 G.* x2) G.* ((G.inverse x2) G.* (G.inverse x1))) G.* (x0 G.* x1)) G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation709{G : Group}(x0 x1 x2 x3 x4 x5 : G): x0 = x0 => equation.group

\lemma grequation710{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x5 G.* ((x0 G.* ((G.inverse x0) G.* (G.inverse x5))) G.* x0)) = x0 => equation.group

\lemma grequation711{G : Group}(x0 x1 : G): (x0 G.* x0) = ((x1 G.* (G.inverse x1)) G.* (x0 G.* x0)) => equation.group

\lemma grequation712{G : Group}(x0 x1 : G): (x0 G.* x1) = (((x0 G.* ((x0 G.* (G.inverse x0)) G.* x1)) G.* (((G.inverse x1) G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x0))) G.* x0)) G.* x1) => equation.group

\lemma grequation713{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x5 = ((x5 G.* (G.inverse x5)) G.* ((x0 G.* (G.inverse x0)) G.* x5)) => equation.group

\lemma grequation714{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x8 G.* ((G.inverse x8) G.* (x6 G.* (G.inverse x6)))) => equation.group

\lemma grequation715{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation716{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x5 G.* (G.inverse x5)) G.* x4) G.* (G.inverse x4)) = ((((x5 G.* (G.inverse x5)) G.* (x0 G.* x4)) G.* (((G.inverse x4) G.* (G.inverse x0)) G.* x5)) G.* (G.inverse x5)) => equation.group

\lemma grequation717{G : Group}(x0 x1 : G): x1 = ((x1 G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation718{G : Group}(x0 x1 x2 x3 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation719{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((((x8 G.* (G.inverse x8)) G.* x12) G.* (((x5 G.* x0) G.* (((G.inverse x0) G.* (G.inverse x5)) G.* x7)) G.* (G.inverse x7))) G.* (((G.inverse x12) G.* x5) G.* x8)) G.* (((G.inverse x8) G.* x11) G.* x8)) = (x5 G.* (x11 G.* x8)) => equation.group

\lemma grequation720{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x4 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x4))) => equation.group

\lemma grequation721{G : Group}(x0 x1 x2 x3 x4 : G): ((x4 G.* (x1 G.* (G.inverse x1))) G.* x3) = ((x2 G.* ((G.inverse x2) G.* x4)) G.* x3) => equation.group

\lemma grequation722{G : Group}(x0 x1 x2 x3 : G): (((x3 G.* ((G.inverse x3) G.* x0)) G.* ((x3 G.* x1) G.* (G.inverse x1))) G.* (G.inverse x3)) = x0 => equation.group

\lemma grequation723{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((x7 G.* (G.inverse x7)) G.* x7) = (x10 G.* (((((x2 G.* (G.inverse x2)) G.* (G.inverse x10)) G.* x2) G.* (G.inverse x2)) G.* ((x7 G.* x8) G.* (G.inverse x8)))) => equation.group

\lemma grequation724{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (((x0 G.* (((G.inverse x0) G.* x0) G.* (G.inverse x0))) G.* x4) G.* (((G.inverse x4) G.* x3) G.* (G.inverse x3))) => equation.group

\lemma grequation725{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x5 G.* (x4 G.* (G.inverse x4))) = (((x5 G.* (x0 G.* x5)) G.* x2) G.* (((x4 G.* x5) G.* x0) G.* (((G.inverse x0) G.* (G.inverse x5)) G.* (((G.inverse x4) G.* ((G.inverse x2) G.* (G.inverse x5))) G.* (G.inverse x0))))) => equation.group

\lemma grequation726{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x5 G.* (G.inverse x5)) = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation727{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x5 G.* (G.inverse x5)) G.* x1) = ((((x1 G.* x3) G.* x1) G.* (G.inverse x1)) G.* (G.inverse x3)) => equation.group

\lemma grequation728{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((((x5 G.* (G.inverse x5)) G.* (x7 G.* (G.inverse x7))) G.* x9) G.* x9) = (((x9 G.* x1) G.* ((G.inverse x1) G.* x9)) G.* (x12 G.* (G.inverse x12))) => equation.group

\lemma grequation729{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x5 G.* (x3 G.* x1)) G.* x1) = (((x5 G.* x3) G.* ((((x1 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x1)) G.* x1)) G.* (x1 G.* (x4 G.* (G.inverse x4)))) => equation.group

\lemma grequation730{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (((x1 G.* ((G.inverse x1) G.* x2)) G.* (G.inverse x2)) G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation731{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x2 = (x0 G.* ((G.inverse x0) G.* x2)) => equation.group

\lemma grequation732{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation733{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x9 G.* ((x14 G.* x10) G.* (G.inverse x10))) G.* (((G.inverse x14) G.* ((x3 G.* x14) G.* x5)) G.* (G.inverse x5))) = ((x9 G.* x3) G.* x14) => equation.group

\lemma grequation734{G : Group}(x0 x1 x2 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation735{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = ((x1 G.* x3) G.* ((((x2 G.* (G.inverse x2)) G.* ((G.inverse x3) G.* (G.inverse x1))) G.* x1) G.* (G.inverse x1))) => equation.group

\lemma grequation736{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* x2) G.* x2) = (x0 G.* (x1 G.* ((G.inverse x1) G.* (x2 G.* x2)))) => equation.group

\lemma grequation737{G : Group}(x0 x1 x2 : G): (x2 G.* ((G.inverse x2) G.* (x0 G.* (G.inverse x0)))) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation738{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x6 G.* x9) G.* (G.inverse x9)) = (((x6 G.* (x9 G.* (G.inverse x9))) G.* (x6 G.* (((G.inverse x6) G.* ((x1 G.* x9) G.* (((G.inverse x9) G.* x10) G.* (x9 G.* (G.inverse x9))))) G.* (G.inverse x10)))) G.* (G.inverse x1)) => equation.group

\lemma grequation739{G : Group}(x0 x1 x2 x3 x4 : G): x1 = (((x3 G.* (G.inverse x3)) G.* (x4 G.* ((G.inverse x4) G.* x1))) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation740{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation741{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* (x2 G.* (G.inverse x2))) = (((((x1 G.* (G.inverse x1)) G.* x1) G.* (G.inverse x1)) G.* (x3 G.* (G.inverse x3))) G.* (x3 G.* ((G.inverse x3) G.* x0))) => equation.group

\lemma grequation742{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x0 G.* (x1 G.* x4)) G.* ((G.inverse x4) G.* x1)) = (((((x0 G.* x1) G.* x5) G.* ((G.inverse x5) G.* (x1 G.* x6))) G.* (G.inverse x6)) G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation743{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x0 = x0 => equation.group

\lemma grequation744{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation745{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = ((x1 G.* ((G.inverse x1) G.* x2)) G.* (((G.inverse x2) G.* x0) G.* (G.inverse x0))) => equation.group

\lemma grequation746{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x1 G.* x9) G.* (G.inverse x9)) = x1 => equation.group

\lemma grequation747{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x2 G.* x4) = (x2 G.* x4) => equation.group

\lemma grequation748{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = ((x0 G.* x0) G.* ((x4 G.* (G.inverse x4)) G.* ((((G.inverse x0) G.* x3) G.* (G.inverse x3)) G.* (G.inverse x0)))) => equation.group

\lemma grequation749{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x1 G.* ((G.inverse x1) G.* x1)) = x1 => equation.group

\lemma grequation750{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x0 = x0 => equation.group

\lemma grequation751{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (((x2 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x2) G.* (x0 G.* (G.inverse x0)))) => equation.group

\lemma grequation752{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x5 G.* (G.inverse x5)) G.* (((x9 G.* ((G.inverse x9) G.* x4)) G.* ((G.inverse x4) G.* x3)) G.* (G.inverse x3))) G.* (((x8 G.* (G.inverse x8)) G.* x5) G.* (((G.inverse x5) G.* x5) G.* (G.inverse x5)))) = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation753{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x2 G.* (((((G.inverse x2) G.* x0) G.* ((G.inverse x0) G.* x0)) G.* ((G.inverse x0) G.* (x7 G.* (G.inverse x7)))) G.* ((x1 G.* (x3 G.* x3)) G.* (x1 G.* (G.inverse x1))))) = ((x1 G.* x3) G.* x3) => equation.group

\lemma grequation754{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x1 G.* (G.inverse x1)) G.* x7) = x7 => equation.group

\lemma grequation755{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x3 G.* x5) G.* ((G.inverse x5) G.* ((G.inverse x3) G.* (x0 G.* ((G.inverse x0) G.* x2))))) = x2 => equation.group

\lemma grequation756{G : Group}(x0 x1 x2 : G): x0 = x0 => equation.group

\lemma grequation757{G : Group}(x0 x1 : G): ((x0 G.* ((G.inverse x0) G.* x0)) G.* (x0 G.* x0)) = ((x0 G.* x0) G.* x0) => equation.group

\lemma grequation758{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x2 G.* ((G.inverse x2) G.* (x7 G.* x9))) = ((x11 G.* (G.inverse x11)) G.* (x7 G.* x9)) => equation.group

\lemma grequation759{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x3 = (((x1 G.* ((G.inverse x1) G.* x9)) G.* (G.inverse x9)) G.* ((x6 G.* (G.inverse x6)) G.* ((x4 G.* (G.inverse x4)) G.* x3))) => equation.group

\lemma grequation760{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation761{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x0 G.* (G.inverse x0)) G.* (x5 G.* (G.inverse x5))) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation762{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* x3) G.* x3) = (x0 G.* (x3 G.* x3)) => equation.group

\lemma grequation763{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x5 G.* x0) G.* (G.inverse x0)) = x5 => equation.group

\lemma grequation764{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation765{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x5 G.* ((G.inverse x5) G.* (x1 G.* (G.inverse x1)))) => equation.group

\lemma grequation766{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x5 G.* (G.inverse x5)) G.* (((x6 G.* (G.inverse x6)) G.* (x1 G.* ((G.inverse x1) G.* x6))) G.* x2)) = ((x6 G.* x5) G.* ((G.inverse x5) G.* x2)) => equation.group

\lemma grequation767{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x9 G.* (G.inverse x9)) = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation768{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x14 G.* (x12 G.* (G.inverse x12))) = (((x3 G.* (((G.inverse x3) G.* x14) G.* x2)) G.* (x6 G.* (G.inverse x6))) G.* ((G.inverse x2) G.* ((G.inverse x14) G.* x14))) => equation.group

\lemma grequation769{G : Group}(x0 x1 x2 : G): ((((x1 G.* ((x0 G.* x0) G.* (((G.inverse x0) G.* x1) G.* x2))) G.* x1) G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x1))) G.* ((G.inverse x2) G.* ((G.inverse x1) G.* (G.inverse x0)))) = x1 => equation.group

\lemma grequation770{G : Group}(x0 x1 x2 x3 : G): (x0 G.* (G.inverse x0)) = ((x1 G.* (((x2 G.* x3) G.* (G.inverse x3)) G.* x1)) G.* ((G.inverse x1) G.* (x1 G.* ((G.inverse x1) G.* ((G.inverse x2) G.* (G.inverse x1)))))) => equation.group

\lemma grequation771{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x5 G.* x0) G.* (G.inverse x0)) = ((x8 G.* x2) G.* (((G.inverse x2) G.* (G.inverse x8)) G.* x5)) => equation.group

\lemma grequation772{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): x2 = ((x5 G.* (G.inverse x5)) G.* x2) => equation.group

\lemma grequation773{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x5 G.* (G.inverse x5)) => equation.group

\lemma grequation774{G : Group}(x0 x1 x2 x3 : G): x3 = x3 => equation.group

\lemma grequation775{G : Group}(x0 x1 x2 x3 : G): G.ide = (x3 G.* (((G.inverse x3) G.* x1) G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x1))))) => equation.group

\lemma grequation776{G : Group}(x0 x1 x2 x3 x4 : G): (((x3 G.* x3) G.* x2) G.* ((G.inverse x2) G.* (x3 G.* (G.inverse x3)))) = ((((x1 G.* ((x2 G.* x0) G.* (x1 G.* (G.inverse x1)))) G.* ((G.inverse x0) G.* (G.inverse x2))) G.* (G.inverse x1)) G.* (x3 G.* x3)) => equation.group

\lemma grequation777{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (((x0 G.* (x0 G.* x8)) G.* ((((G.inverse x8) G.* x9) G.* (G.inverse x9)) G.* (x6 G.* ((G.inverse x6) G.* (G.inverse x0))))) G.* (((x3 G.* (G.inverse x3)) G.* ((G.inverse x0) G.* x1)) G.* (G.inverse x1))) => equation.group

\lemma grequation778{G : Group}(x0 x1 x2 x3 x4 : G): (((x0 G.* (x3 G.* (x4 G.* (G.inverse x4)))) G.* (((G.inverse x3) G.* x3) G.* (G.inverse x3))) G.* (x0 G.* x3)) = (x0 G.* (x0 G.* x3)) => equation.group

\lemma grequation779{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x7 = x7 => equation.group

\lemma grequation780{G : Group}(x0 x1 : G): (x1 G.* ((G.inverse x1) G.* x1)) = (x0 G.* ((G.inverse x0) G.* x1)) => equation.group

\lemma grequation781{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = ((((x3 G.* x6) G.* (G.inverse x6)) G.* x5) G.* ((x1 G.* (((G.inverse x1) G.* (G.inverse x5)) G.* (G.inverse x3))) G.* (x4 G.* (G.inverse x4)))) => equation.group

\lemma grequation782{G : Group}(x0 x1 x2 : G): x1 = (((x1 G.* x1) G.* x1) G.* (((x2 G.* ((x1 G.* (G.inverse x1)) G.* x2)) G.* (((G.inverse x2) G.* (G.inverse x2)) G.* ((G.inverse x1) G.* (G.inverse x1)))) G.* (((x2 G.* (G.inverse x2)) G.* (G.inverse x1)) G.* x1))) => equation.group

\lemma grequation783{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x5 G.* ((G.inverse x5) G.* x0)) = (x6 G.* ((G.inverse x6) G.* x0)) => equation.group

\lemma grequation784{G : Group}(x0 x1 x2 x3 : G): x1 = (x1 G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation785{G : Group}(x0 x1 x2 x3 x4 : G): (x3 G.* (((G.inverse x3) G.* x2) G.* (G.inverse x2))) = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation786{G : Group}(x0 x1 x2 x3 x4 : G): ((x3 G.* (x0 G.* (G.inverse x0))) G.* ((G.inverse x3) G.* x4)) = ((x4 G.* x3) G.* (((x4 G.* x1) G.* (((G.inverse x1) G.* (x0 G.* (G.inverse x0))) G.* x4)) G.* (((G.inverse x4) G.* x4) G.* ((G.inverse x4) G.* ((G.inverse x4) G.* (G.inverse x3)))))) => equation.group

\lemma grequation787{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x8 G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x8)))) = (x7 G.* ((G.inverse x7) G.* (x6 G.* (G.inverse x6)))) => equation.group

\lemma grequation788{G : Group}(x0 x1 x2 x3 : G): (x3 G.* x0) = ((x3 G.* x2) G.* ((G.inverse x2) G.* x0)) => equation.group

\lemma grequation789{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x4 G.* ((G.inverse x4) G.* x3)) = x3 => equation.group

\lemma grequation790{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x2 G.* (((G.inverse x2) G.* x5) G.* (G.inverse x5))) = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation791{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x6 = x6 => equation.group

\lemma grequation792{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x7 G.* (G.inverse x7)) G.* (x4 G.* (G.inverse x4))) = ((x0 G.* (G.inverse x0)) G.* ((x4 G.* x9) G.* ((G.inverse x9) G.* (G.inverse x4)))) => equation.group

\lemma grequation793{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x3 G.* (G.inverse x3)) G.* x0) = x0 => equation.group

\lemma grequation794{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x4 G.* ((((G.inverse x4) G.* x7) G.* (((G.inverse x7) G.* (((x5 G.* (G.inverse x5)) G.* x0) G.* (G.inverse x0))) G.* x7)) G.* (G.inverse x7))) = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation795{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation796{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x4 G.* (x2 G.* ((G.inverse x2) G.* (G.inverse x4)))) => equation.group

\lemma grequation797{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x0 G.* (x8 G.* (G.inverse x8))) = x0 => equation.group

\lemma grequation798{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x5 = x5 => equation.group

\lemma grequation799{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (((((x2 G.* x5) G.* ((G.inverse x5) G.* (G.inverse x2))) G.* (x2 G.* x5)) G.* ((x3 G.* (G.inverse x3)) G.* (G.inverse x5))) G.* (G.inverse x2)) => equation.group

\lemma grequation800{G : Group}(x0 x1 : G): x0 = x0 => equation.group

\lemma grequation801{G : Group}(x0 x1 : G): (x1 G.* (G.inverse x1)) = (x1 G.* (x1 G.* ((x1 G.* (G.inverse x1)) G.* ((G.inverse x1) G.* (G.inverse x1))))) => equation.group

\lemma grequation802{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (((x0 G.* x3) G.* (G.inverse x3)) G.* (G.inverse x0)) => equation.group

\lemma grequation803{G : Group}(x0 x1 : G): x0 = (x0 G.* ((G.inverse x0) G.* (x0 G.* ((G.inverse x0) G.* x0)))) => equation.group

\lemma grequation804{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x2 G.* (x9 G.* x6)) = ((x2 G.* x9) G.* (x6 G.* (x9 G.* (G.inverse x9)))) => equation.group

\lemma grequation805{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x1 G.* ((G.inverse x1) G.* (x3 G.* (((G.inverse x3) G.* (x1 G.* x5)) G.* (G.inverse x5))))) = x1 => equation.group

\lemma grequation806{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x2 = ((x10 G.* (G.inverse x10)) G.* x2) => equation.group

\lemma grequation807{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x11 G.* (G.inverse x11)) G.* x2) = (((x3 G.* (G.inverse x3)) G.* (x5 G.* ((G.inverse x5) G.* x6))) G.* ((x5 G.* (((x9 G.* (G.inverse x9)) G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x5))) G.* (x3 G.* (((G.inverse x3) G.* (G.inverse x6)) G.* x2)))) => equation.group

\lemma grequation808{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = ((x8 G.* (x8 G.* x8)) G.* ((x2 G.* (G.inverse x2)) G.* ((G.inverse x8) G.* ((G.inverse x8) G.* (G.inverse x8))))) => equation.group

\lemma grequation809{G : Group}(x0 x1 : G): (x0 G.* (G.inverse x0)) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation810{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x1 = (x1 G.* (x5 G.* (G.inverse x5))) => equation.group

\lemma grequation811{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x0 G.* (G.inverse x0)) = (((x10 G.* x8) G.* (x8 G.* (G.inverse x8))) G.* ((G.inverse x8) G.* (G.inverse x10))) => equation.group

\lemma grequation812{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x1 G.* (G.inverse x1)) = (((x9 G.* ((x0 G.* (x7 G.* x5)) G.* (((x6 G.* x4) G.* (G.inverse x4)) G.* ((G.inverse x6) G.* (G.inverse x5))))) G.* (G.inverse x7)) G.* ((G.inverse x0) G.* (G.inverse x9))) => equation.group

\lemma grequation813{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((((x4 G.* x6) G.* (x3 G.* (x2 G.* (G.inverse x2)))) G.* (G.inverse x3)) G.* ((x1 G.* ((G.inverse x1) G.* ((G.inverse x6) G.* (G.inverse x4)))) G.* x9)) = (x9 G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation814{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x2 G.* ((((G.inverse x2) G.* x4) G.* (G.inverse x4)) G.* (x3 G.* ((G.inverse x3) G.* x1)))) = (((x3 G.* (G.inverse x3)) G.* (x2 G.* (((G.inverse x2) G.* (x4 G.* (((G.inverse x4) G.* x1) G.* (G.inverse x1)))) G.* x1))) G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation815{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x2 G.* ((G.inverse x2) G.* x1)) = (x1 G.* (x7 G.* (G.inverse x7))) => equation.group

\lemma grequation816{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x7 G.* (G.inverse x7)) => equation.group

\lemma grequation817{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x6 G.* ((G.inverse x6) G.* x0)) = ((x0 G.* (x4 G.* (x5 G.* (G.inverse x5)))) G.* (G.inverse x4)) => equation.group

\lemma grequation818{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x3 = x3 => equation.group

\lemma grequation819{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x3 G.* ((G.inverse x3) G.* x1)) G.* ((x2 G.* x1) G.* (G.inverse x1))) = (x1 G.* x2) => equation.group

\lemma grequation820{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* x1) = ((((x3 G.* (((G.inverse x3) G.* x3) G.* (G.inverse x3))) G.* x2) G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x2)))) G.* (x3 G.* x1)) => equation.group

\lemma grequation821{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x8 G.* (x6 G.* x2)) = (x8 G.* ((x6 G.* x2) G.* (x3 G.* (G.inverse x3)))) => equation.group

\lemma grequation822{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((x3 G.* (x8 G.* ((x10 G.* (G.inverse x10)) G.* (G.inverse x8)))) G.* (G.inverse x3)) => equation.group

\lemma grequation823{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x11 = (((((x5 G.* x6) G.* (G.inverse x6)) G.* ((G.inverse x5) G.* x11)) G.* x3) G.* (G.inverse x3)) => equation.group

\lemma grequation824{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x6 G.* (G.inverse x6)) G.* ((x6 G.* (G.inverse x6)) G.* (x3 G.* x3))) = (((x3 G.* (x3 G.* x1)) G.* (G.inverse x1)) G.* (x8 G.* (G.inverse x8))) => equation.group

\lemma grequation825{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x8 G.* (G.inverse x8)) = (((x6 G.* (G.inverse x6)) G.* x7) G.* ((G.inverse x7) G.* (x8 G.* (G.inverse x8)))) => equation.group

\lemma grequation826{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x3 G.* x1) = (x3 G.* x1) => equation.group

\lemma grequation827{G : Group}(x0 x1 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation828{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x4 G.* (G.inverse x4)) = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation829{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x10 = ((x10 G.* (x9 G.* (x7 G.* (G.inverse x7)))) G.* (x8 G.* (((G.inverse x8) G.* (G.inverse x9)) G.* (x4 G.* (G.inverse x4))))) => equation.group

\lemma grequation830{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x8 G.* (G.inverse x8)) = ((((x2 G.* x10) G.* (x9 G.* x6)) G.* (x2 G.* ((G.inverse x2) G.* x5))) G.* ((x3 G.* ((G.inverse x3) G.* x0)) G.* (((((G.inverse x0) G.* (G.inverse x5)) G.* (G.inverse x6)) G.* ((G.inverse x9) G.* (G.inverse x10))) G.* (G.inverse x2)))) => equation.group

\lemma grequation831{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x5 = (x5 G.* ((G.inverse x5) G.* x5)) => equation.group

\lemma grequation832{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x3 = ((x3 G.* (x3 G.* x9)) G.* ((G.inverse x9) G.* (G.inverse x3))) => equation.group

\lemma grequation833{G : Group}(x0 x1 x2 : G): ((x1 G.* x2) G.* ((G.inverse x2) G.* (G.inverse x1))) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation834{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x3 = x3 => equation.group

\lemma grequation835{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x7 G.* (x5 G.* x6)) G.* (G.inverse x6)) = (x7 G.* (x5 G.* (x6 G.* (G.inverse x6)))) => equation.group

\lemma grequation836{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x7 G.* x0) G.* x8) G.* (G.inverse x8)) = (((x7 G.* x0) G.* (x7 G.* (x9 G.* x4))) G.* (((G.inverse x4) G.* (G.inverse x9)) G.* (G.inverse x7))) => equation.group

\lemma grequation837{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x0 G.* (G.inverse x0)) G.* x6) = ((x6 G.* (x1 G.* x2)) G.* (((G.inverse x2) G.* x2) G.* (((G.inverse x2) G.* (((G.inverse x1) G.* x6) G.* (G.inverse x6))) G.* (x5 G.* (G.inverse x5))))) => equation.group

\lemma grequation838{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x6 G.* x6) G.* ((G.inverse x6) G.* (x0 G.* x5))) = ((x6 G.* (((x0 G.* x0) G.* (x3 G.* (G.inverse x3))) G.* (G.inverse x0))) G.* x5) => equation.group

\lemma grequation839{G : Group}(x0 x1 x2 x3 : G): (x3 G.* (x2 G.* (G.inverse x2))) = (x0 G.* ((G.inverse x0) G.* x3)) => equation.group

\lemma grequation840{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x12 G.* (((G.inverse x12) G.* (x1 G.* x1)) G.* (G.inverse x1))) = x1 => equation.group

\lemma grequation841{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x4 G.* (G.inverse x4)) G.* ((x0 G.* x0) G.* (G.inverse x0))) = x0 => equation.group

\lemma grequation842{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x6 = ((x6 G.* (x3 G.* x13)) G.* ((G.inverse x13) G.* (G.inverse x3))) => equation.group

\lemma grequation843{G : Group}(x0 x1 x2 : G): (x2 G.* ((G.inverse x2) G.* x2)) = ((((x1 G.* x0) G.* x0) G.* (G.inverse x0)) G.* (((x0 G.* ((G.inverse x0) G.* (G.inverse x0))) G.* (((G.inverse x1) G.* (x0 G.* x1)) G.* (G.inverse x1))) G.* ((G.inverse x0) G.* x2))) => equation.group

\lemma grequation844{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = ((x6 G.* (x6 G.* x4)) G.* (((G.inverse x4) G.* (G.inverse x6)) G.* (G.inverse x6))) => equation.group

\lemma grequation845{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (((x4 G.* x9) G.* (G.inverse x9)) G.* (G.inverse x4)) => equation.group

\lemma grequation846{G : Group}(x0 x1 x2 : G): x2 = x2 => equation.group

\lemma grequation847{G : Group}(x0 x1 : G): x1 = ((((x1 G.* x1) G.* ((G.inverse x1) G.* ((G.inverse x1) G.* x1))) G.* (((G.inverse x1) G.* x1) G.* (G.inverse x1))) G.* (x0 G.* ((G.inverse x0) G.* x1))) => equation.group

\lemma grequation848{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (x4 G.* (G.inverse x4)) = (((x10 G.* x0) G.* (G.inverse x0)) G.* (G.inverse x10)) => equation.group

\lemma grequation849{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x13 G.* (G.inverse x13)) = (x10 G.* (G.inverse x10)) => equation.group

\lemma grequation850{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((((x1 G.* (G.inverse x1)) G.* (x9 G.* (G.inverse x9))) G.* ((((x4 G.* x9) G.* x8) G.* (G.inverse x8)) G.* x7)) G.* ((G.inverse x7) G.* (G.inverse x9))) = x4 => equation.group

\lemma grequation851{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x5 G.* x4) G.* x5) G.* ((G.inverse x5) G.* (G.inverse x4))) = ((x5 G.* (x1 G.* (G.inverse x1))) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation852{G : Group}(x0 x1 : G): ((x0 G.* x0) G.* (x0 G.* (((x1 G.* (G.inverse x1)) G.* ((G.inverse x0) G.* (x1 G.* (G.inverse x1)))) G.* (G.inverse x0)))) = x0 => equation.group

\lemma grequation853{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x4 G.* x3) G.* x0) G.* (((G.inverse x0) G.* x2) G.* ((x10 G.* ((G.inverse x10) G.* (G.inverse x2))) G.* (((G.inverse x3) G.* (G.inverse x4)) G.* (x7 G.* x2))))) = ((x7 G.* x8) G.* ((G.inverse x8) G.* x2)) => equation.group

\lemma grequation854{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x4 G.* (G.inverse x4)) => equation.group

\lemma grequation855{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (x2 G.* (G.inverse x2)) = (x8 G.* (G.inverse x8)) => equation.group

\lemma grequation856{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = ((x6 G.* ((G.inverse x6) G.* x12)) G.* (G.inverse x12)) => equation.group

\lemma grequation857{G : Group}(x0 x1 x2 : G): (((x1 G.* x1) G.* x2) G.* ((((G.inverse x2) G.* x2) G.* x1) G.* ((G.inverse x1) G.* ((G.inverse x2) G.* (G.inverse x1))))) = x1 => equation.group

\lemma grequation858{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x13 G.* ((G.inverse x13) G.* x10)) = x10 => equation.group

\lemma grequation859{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x2 G.* (x0 G.* (G.inverse x0))) G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x2)))) => equation.group

\lemma grequation860{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x0 G.* x2) G.* (G.inverse x2)) = (((x9 G.* x13) G.* (G.inverse x13)) G.* ((G.inverse x9) G.* ((x0 G.* (G.inverse x0)) G.* x0))) => equation.group

\lemma grequation861{G : Group}(x0 x1 x2 x3 : G): ((x2 G.* (x1 G.* x2)) G.* x3) = (x2 G.* ((x1 G.* ((x2 G.* x3) G.* ((((x0 G.* (x1 G.* x1)) G.* x2) G.* (G.inverse x2)) G.* ((G.inverse x1) G.* x2)))) G.* (((G.inverse x2) G.* (G.inverse x1)) G.* (G.inverse x0)))) => equation.group

\lemma grequation862{G : Group}(x0 x1 x2 : G): (x0 G.* ((x0 G.* (G.inverse x0)) G.* (G.inverse x0))) = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation863{G : Group}(x0 x1 x2 x3 x4 : G): (x0 G.* ((G.inverse x0) G.* x1)) = x1 => equation.group

\lemma grequation864{G : Group}(x0 x1 x2 x3 x4 : G): (((x3 G.* (G.inverse x3)) G.* x2) G.* x3) = (x2 G.* x3) => equation.group

\lemma grequation865{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (((x12 G.* (G.inverse x12)) G.* ((x11 G.* ((G.inverse x11) G.* (x5 G.* (G.inverse x5)))) G.* (x12 G.* (x10 G.* (G.inverse x10))))) G.* ((G.inverse x12) G.* x4)) = (((x3 G.* (G.inverse x3)) G.* (((x3 G.* (G.inverse x3)) G.* x4) G.* x13)) G.* (G.inverse x13)) => equation.group

\lemma grequation866{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation867{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x2 = (x1 G.* ((G.inverse x1) G.* x2)) => equation.group

\lemma grequation868{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x4 G.* (((x2 G.* (G.inverse x2)) G.* x2) G.* ((G.inverse x2) G.* (x4 G.* ((G.inverse x4) G.* (G.inverse x4)))))) => equation.group

\lemma grequation869{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((x7 G.* (G.inverse x7)) G.* (x13 G.* (x9 G.* (G.inverse x9)))) = ((x13 G.* x12) G.* (G.inverse x12)) => equation.group

\lemma grequation870{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* (G.inverse x0)) G.* x2) = ((x2 G.* x0) G.* ((G.inverse x0) G.* (x0 G.* (G.inverse x0)))) => equation.group

\lemma grequation871{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x4 G.* (((G.inverse x4) G.* (x7 G.* (G.inverse x7))) G.* x7)) G.* x0) = (x7 G.* x0) => equation.group

\lemma grequation872{G : Group}(x0 x1 x2 x3 x4 x5 : G): (((x0 G.* (G.inverse x0)) G.* (x5 G.* (G.inverse x5))) G.* (x5 G.* (x4 G.* ((G.inverse x4) G.* (G.inverse x5))))) = ((x5 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x5))) => equation.group

\lemma grequation873{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (((x7 G.* x6) G.* (G.inverse x6)) G.* (G.inverse x7)) => equation.group

\lemma grequation874{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x5 G.* ((G.inverse x5) G.* (x5 G.* x8))) G.* ((x5 G.* (x0 G.* (G.inverse x0))) G.* ((((G.inverse x5) G.* (x4 G.* (G.inverse x4))) G.* (G.inverse x8)) G.* ((G.inverse x5) G.* x4)))) G.* (x7 G.* (G.inverse x7))) = x4 => equation.group

\lemma grequation875{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (((x8 G.* x4) G.* (x4 G.* ((((G.inverse x4) G.* x1) G.* ((G.inverse x1) G.* x3)) G.* (G.inverse x3)))) G.* (G.inverse x4)) = x8 => equation.group

\lemma grequation876{G : Group}(x0 x1 : G): x1 = x1 => equation.group

\lemma grequation877{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x4 G.* x5) G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x5))) = ((x4 G.* x1) G.* ((G.inverse x1) G.* (x4 G.* (G.inverse x4)))) => equation.group

\lemma grequation878{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation879{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x2 G.* x4) G.* (G.inverse x4)) = (x4 G.* ((G.inverse x4) G.* x2)) => equation.group

\lemma grequation880{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (((x9 G.* (G.inverse x9)) G.* ((x8 G.* x8) G.* (G.inverse x8))) G.* (x2 G.* (((G.inverse x2) G.* x2) G.* (G.inverse x2)))) = x8 => equation.group

\lemma grequation881{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x10 = x10 => equation.group

\lemma grequation882{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): ((x7 G.* x2) G.* (G.inverse x2)) = x7 => equation.group

\lemma grequation883{G : Group}(x0 x1 x2 x3 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation884{G : Group}(x0 x1 x2 : G): x1 = ((x1 G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation885{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x7 G.* (x8 G.* ((G.inverse x8) G.* (G.inverse x7)))) => equation.group

\lemma grequation886{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): x3 = (x10 G.* ((G.inverse x10) G.* x3)) => equation.group

\lemma grequation887{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x0 G.* (((x2 G.* x1) G.* ((((G.inverse x1) G.* (G.inverse x2)) G.* (G.inverse x0)) G.* (x5 G.* x1))) G.* x4)) = (x5 G.* (x1 G.* x4)) => equation.group

\lemma grequation888{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x13 G.* (G.inverse x13)) => equation.group

\lemma grequation889{G : Group}(x0 x1 x2 x3 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation890{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation891{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x4 G.* (G.inverse x4)) = (x6 G.* (G.inverse x6)) => equation.group

\lemma grequation892{G : Group}(x0 x1 x2 : G): ((x0 G.* ((G.inverse x0) G.* x1)) G.* (((x1 G.* x0) G.* (G.inverse x0)) G.* (x2 G.* (G.inverse x2)))) = (x1 G.* x1) => equation.group

\lemma grequation893{G : Group}(x0 x1 x2 x3 : G): ((x1 G.* ((G.inverse x1) G.* x0)) G.* (((x1 G.* ((x3 G.* ((G.inverse x3) G.* ((x0 G.* x1) G.* x0))) G.* (G.inverse x0))) G.* ((x0 G.* (G.inverse x0)) G.* ((G.inverse x1) G.* (G.inverse x0)))) G.* (G.inverse x1))) = x0 => equation.group

\lemma grequation894{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x6 = (x6 G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation895{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (x3 G.* (G.inverse x3)) => equation.group

\lemma grequation896{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x10 = (((x10 G.* x3) G.* (((G.inverse x3) G.* x2) G.* (x3 G.* (G.inverse x3)))) G.* (G.inverse x2)) => equation.group

\lemma grequation897{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): G.ide = (x2 G.* (G.inverse x2)) => equation.group

\lemma grequation898{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation899{G : Group}(x0 x1 x2 : G): x2 = x2 => equation.group

\lemma grequation900{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): ((x9 G.* (G.inverse x9)) G.* x6) = (x6 G.* ((x9 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x9)))) => equation.group

\lemma grequation901{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = ((x1 G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x1)))) G.* ((x4 G.* ((G.inverse x4) G.* x1)) G.* (((G.inverse x1) G.* x0) G.* (G.inverse x0)))) => equation.group

\lemma grequation902{G : Group}(x0 x1 : G): ((x0 G.* x0) G.* (x1 G.* (G.inverse x1))) = ((x0 G.* x0) G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation903{G : Group}(x0 x1 x2 x3 x4 x5 : G): ((x1 G.* x4) G.* ((G.inverse x4) G.* x2)) = (((x1 G.* x5) G.* (G.inverse x5)) G.* x2) => equation.group

\lemma grequation904{G : Group}(x0 x1 x2 : G): ((((x1 G.* (G.inverse x1)) G.* x2) G.* ((G.inverse x2) G.* x1)) G.* (((G.inverse x1) G.* x2) G.* ((G.inverse x2) G.* x1))) = x1 => equation.group

\lemma grequation905{G : Group}(x0 x1 x2 : G): x0 = ((x0 G.* (((x1 G.* x2) G.* x2) G.* (x2 G.* ((G.inverse x2) G.* ((G.inverse x2) G.* (G.inverse x2)))))) G.* (G.inverse x1)) => equation.group

\lemma grequation906{G : Group}(x0 x1 : G): G.ide = (x0 G.* ((x0 G.* (((G.inverse x0) G.* x1) G.* (G.inverse x1))) G.* (G.inverse x0))) => equation.group

\lemma grequation907{G : Group}(x0 x1 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation908{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((((x2 G.* x3) G.* x11) G.* (x4 G.* (G.inverse x4))) G.* (((x2 G.* x2) G.* x11) G.* ((x7 G.* (G.inverse x7)) G.* (((G.inverse x11) G.* (G.inverse x2)) G.* ((G.inverse x2) G.* (G.inverse x11)))))) = (x2 G.* x3) => equation.group

\lemma grequation909{G : Group}(x0 x1 x2 : G): (((x1 G.* x2) G.* (G.inverse x2)) G.* x2) = (x1 G.* x2) => equation.group

\lemma grequation910{G : Group}(x0 x1 x2 x3 x4 : G): ((x3 G.* (x1 G.* x2)) G.* (((((G.inverse x2) G.* ((G.inverse x1) G.* (G.inverse x3))) G.* (x2 G.* (G.inverse x2))) G.* (x3 G.* x3)) G.* x2)) = (((x3 G.* x3) G.* (x2 G.* x2)) G.* (G.inverse x2)) => equation.group

\lemma grequation911{G : Group}(x0 x1 x2 : G): (((x2 G.* x2) G.* x1) G.* (x0 G.* (((G.inverse x0) G.* (x0 G.* (G.inverse x0))) G.* (G.inverse x1)))) = (x2 G.* x2) => equation.group

\lemma grequation912{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x5 G.* ((x5 G.* (((G.inverse x5) G.* (G.inverse x5)) G.* (x2 G.* (G.inverse x2)))) G.* (x0 G.* (G.inverse x0)))) => equation.group

\lemma grequation913{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): ((x10 G.* (G.inverse x10)) G.* ((x1 G.* (G.inverse x1)) G.* x8)) = x8 => equation.group

\lemma grequation914{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x4 = ((x4 G.* (x5 G.* x6)) G.* (((G.inverse x6) G.* (G.inverse x5)) G.* ((x0 G.* (G.inverse x0)) G.* (x7 G.* (G.inverse x7))))) => equation.group

\lemma grequation915{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((((x1 G.* x1) G.* x1) G.* x5) G.* (((G.inverse x5) G.* x3) G.* (((x5 G.* (x1 G.* (G.inverse x1))) G.* ((G.inverse x5) G.* (G.inverse x3))) G.* (G.inverse x1)))) = (x1 G.* x1) => equation.group

\lemma grequation916{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation917{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (((x1 G.* (G.inverse x1)) G.* x2) G.* ((x6 G.* ((G.inverse x6) G.* x6)) G.* (((G.inverse x6) G.* x3) G.* ((G.inverse x3) G.* x0)))) = (x2 G.* x0) => equation.group

\lemma grequation918{G : Group}(x0 x1 x2 x3 : G): G.ide = ((x3 G.* x1) G.* ((G.inverse x1) G.* (G.inverse x3))) => equation.group

\lemma grequation919{G : Group}(x0 x1 x2 : G): (x2 G.* x1) = ((x2 G.* (G.inverse x2)) G.* (x2 G.* x1)) => equation.group

\lemma grequation920{G : Group}(x0 x1 : G): x1 = x1 => equation.group

\lemma grequation921{G : Group}(x0 x1 x2 x3 x4 : G): x1 = (x1 G.* (x4 G.* (G.inverse x4))) => equation.group

\lemma grequation922{G : Group}(x0 x1 x2 x3 x4 : G): (x2 G.* ((G.inverse x2) G.* (x0 G.* (G.inverse x0)))) = (((x2 G.* (((G.inverse x2) G.* x3) G.* x2)) G.* ((((G.inverse x2) G.* x2) G.* x0) G.* (G.inverse x0))) G.* ((G.inverse x2) G.* (G.inverse x3))) => equation.group

\lemma grequation923{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x6 = x6 => equation.group

\lemma grequation924{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x5 G.* (x7 G.* x2)) G.* (((((x1 G.* (G.inverse x1)) G.* ((((x2 G.* (G.inverse x2)) G.* (x3 G.* x6)) G.* ((G.inverse x6) G.* (x6 G.* x5))) G.* ((G.inverse x5) G.* x3))) G.* (G.inverse x3)) G.* (((G.inverse x6) G.* (G.inverse x3)) G.* (G.inverse x2))) G.* (G.inverse x7))) = x5 => equation.group

\lemma grequation925{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x1 G.* x5) G.* ((G.inverse x5) G.* (G.inverse x1))) = ((((((x10 G.* x3) G.* (G.inverse x3)) G.* ((G.inverse x10) G.* x5)) G.* (G.inverse x5)) G.* ((x3 G.* ((G.inverse x3) G.* x11)) G.* (G.inverse x11))) G.* (x3 G.* (G.inverse x3))) => equation.group

\lemma grequation926{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((((x12 G.* (G.inverse x12)) G.* (x5 G.* (G.inverse x5))) G.* x0) G.* ((((x2 G.* (G.inverse x2)) G.* (G.inverse x0)) G.* x10) G.* x0)) = (x10 G.* (x0 G.* (x8 G.* (G.inverse x8)))) => equation.group

\lemma grequation927{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x3 = (x3 G.* (x0 G.* (G.inverse x0))) => equation.group

\lemma grequation928{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x0 = (x0 G.* (x1 G.* (G.inverse x1))) => equation.group

\lemma grequation929{G : Group}(x0 x1 x2 x3 : G): (x0 G.* (G.inverse x0)) = ((x2 G.* (G.inverse x2)) G.* ((x1 G.* x0) G.* ((G.inverse x0) G.* (G.inverse x1)))) => equation.group

\lemma grequation930{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x7 G.* (((G.inverse x7) G.* x12) G.* (G.inverse x12))) = ((x7 G.* ((x9 G.* (G.inverse x9)) G.* (G.inverse x7))) G.* (x10 G.* (G.inverse x10))) => equation.group

\lemma grequation931{G : Group}(x0 x1 : G): (x0 G.* (x0 G.* (G.inverse x0))) = x0 => equation.group

\lemma grequation932{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = ((x9 G.* ((G.inverse x9) G.* (((((x2 G.* ((G.inverse x2) G.* x1)) G.* ((G.inverse x1) G.* (x5 G.* (G.inverse x5)))) G.* (x1 G.* x7)) G.* x8) G.* ((G.inverse x8) G.* x3)))) G.* ((G.inverse x3) G.* ((G.inverse x7) G.* (G.inverse x1)))) => equation.group

\lemma grequation933{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x7 G.* ((x6 G.* x5) G.* (G.inverse x5))) = (x7 G.* x6) => equation.group

\lemma grequation934{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (x1 G.* ((G.inverse x1) G.* x2)) = x2 => equation.group

\lemma grequation935{G : Group}(x0 x1 x2 x3 : G): ((x0 G.* ((G.inverse x0) G.* x1)) G.* ((G.inverse x1) G.* x1)) = x1 => equation.group

\lemma grequation936{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): (((x0 G.* ((x6 G.* (G.inverse x6)) G.* (G.inverse x0))) G.* (x2 G.* x6)) G.* (((G.inverse x6) G.* x8) G.* (G.inverse x8))) = (((((x6 G.* x8) G.* (G.inverse x8)) G.* (G.inverse x6)) G.* (x7 G.* (G.inverse x7))) G.* x2) => equation.group

\lemma grequation937{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): (x8 G.* (x0 G.* (G.inverse x0))) = x8 => equation.group

\lemma grequation938{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x4 G.* (((G.inverse x4) G.* x5) G.* (G.inverse x5))) G.* (x0 G.* x1)) = ((x0 G.* (x1 G.* x0)) G.* ((x5 G.* ((G.inverse x5) G.* ((G.inverse x0) G.* x5))) G.* (G.inverse x5))) => equation.group

\lemma grequation939{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x5 G.* (x5 G.* (G.inverse x5))) = x5 => equation.group

\lemma grequation940{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): (x6 G.* ((G.inverse x6) G.* x8)) = x8 => equation.group

\lemma grequation941{G : Group}(x0 x1 x2 : G): x2 = ((x1 G.* (((x1 G.* (G.inverse x1)) G.* ((G.inverse x1) G.* (x0 G.* (G.inverse x0)))) G.* (x2 G.* (G.inverse x2)))) G.* ((x2 G.* (G.inverse x2)) G.* x2)) => equation.group

\lemma grequation942{G : Group}(x0 x1 x2 x3 x4 : G): ((x1 G.* (((x2 G.* ((G.inverse x2) G.* (G.inverse x1))) G.* x3) G.* ((x1 G.* (G.inverse x1)) G.* (x2 G.* x2)))) G.* (x4 G.* (G.inverse x4))) = ((x3 G.* x2) G.* x2) => equation.group

\lemma grequation943{G : Group}(x0 x1 : G): ((x0 G.* (G.inverse x0)) G.* (((x0 G.* (x1 G.* (G.inverse x1))) G.* (G.inverse x0)) G.* x0)) = x0 => equation.group

\lemma grequation944{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): (((x6 G.* x3) G.* x0) G.* (G.inverse x0)) = (x6 G.* x3) => equation.group

\lemma grequation945{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): x4 = ((x13 G.* ((x8 G.* ((G.inverse x8) G.* (G.inverse x13))) G.* (x4 G.* x6))) G.* (G.inverse x6)) => equation.group

\lemma grequation946{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((((x6 G.* ((G.inverse x6) G.* x2)) G.* x10) G.* x7) G.* ((G.inverse x7) G.* x5)) = (x2 G.* (x10 G.* x5)) => equation.group

\lemma grequation947{G : Group}(x0 x1 x2 : G): ((x1 G.* (G.inverse x1)) G.* x2) = (x2 G.* (x0 G.* ((x1 G.* (G.inverse x1)) G.* (G.inverse x0)))) => equation.group

\lemma grequation948{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): ((x6 G.* (G.inverse x6)) G.* x0) = x0 => equation.group

\lemma grequation949{G : Group}(x0 x1 x2 x3 : G): G.ide = (x3 G.* (x3 G.* ((G.inverse x3) G.* (G.inverse x3)))) => equation.group

\lemma grequation950{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): G.ide = (((x5 G.* x5) G.* (G.inverse x5)) G.* (((x3 G.* (G.inverse x3)) G.* (x5 G.* ((G.inverse x5) G.* (G.inverse x5)))) G.* ((x3 G.* (G.inverse x3)) G.* (x2 G.* (G.inverse x2))))) => equation.group

\lemma grequation951{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x2 G.* ((x3 G.* x1) G.* (G.inverse x1))) = ((x2 G.* (G.inverse x2)) G.* (x2 G.* x3)) => equation.group

\lemma grequation952{G : Group}(x0 x1 : G): (x1 G.* (G.inverse x1)) = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation953{G : Group}(x0 x1 x2 x3 x4 x5 : G): G.ide = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation954{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): ((x5 G.* x5) G.* (x7 G.* (G.inverse x7))) = (x5 G.* x5) => equation.group

\lemma grequation955{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): (x5 G.* x12) = (x5 G.* ((x12 G.* x3) G.* (G.inverse x3))) => equation.group

\lemma grequation956{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (((x11 G.* x5) G.* (G.inverse x5)) G.* (G.inverse x11)) => equation.group

\lemma grequation957{G : Group}(x0 x1 x2 x3 x4 x5 : G): (x2 G.* (((G.inverse x2) G.* x2) G.* ((G.inverse x2) G.* x1))) = x1 => equation.group

\lemma grequation958{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (((x6 G.* (x6 G.* (x0 G.* x7))) G.* x11) G.* (x2 G.* (G.inverse x2))) = ((x6 G.* x6) G.* ((x0 G.* x7) G.* x11)) => equation.group

\lemma grequation959{G : Group}(x0 x1 x2 : G): ((x0 G.* (G.inverse x0)) G.* x0) = (x0 G.* (x2 G.* (G.inverse x2))) => equation.group

\lemma grequation960{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x2 G.* (G.inverse x2)) = (x2 G.* (x2 G.* ((((G.inverse x2) G.* (G.inverse x2)) G.* x6) G.* (G.inverse x6)))) => equation.group

\lemma grequation961{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): x8 = (((x8 G.* x13) G.* ((G.inverse x13) G.* x0)) G.* (G.inverse x0)) => equation.group

\lemma grequation962{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): x6 = ((x8 G.* (G.inverse x8)) G.* x6) => equation.group

\lemma grequation963{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): x1 = ((x4 G.* x1) G.* (((((G.inverse x1) G.* x7) G.* (G.inverse x7)) G.* ((x7 G.* (G.inverse x7)) G.* (G.inverse x4))) G.* (x3 G.* ((G.inverse x3) G.* x1)))) => equation.group

\lemma grequation964{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): x3 = (((x2 G.* x5) G.* ((G.inverse x5) G.* (G.inverse x2))) G.* x3) => equation.group

\lemma grequation965{G : Group}(x0 x1 x2 x3 : G): (((((x0 G.* x1) G.* ((G.inverse x1) G.* (G.inverse x0))) G.* (x3 G.* x0)) G.* ((G.inverse x0) G.* (G.inverse x3))) G.* x3) = ((x3 G.* x1) G.* (G.inverse x1)) => equation.group

\lemma grequation966{G : Group}(x0 x1 x2 x3 : G): (x1 G.* (x3 G.* (G.inverse x3))) = x1 => equation.group

\lemma grequation967{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x0 G.* ((G.inverse x0) G.* (x8 G.* x0))) G.* (x0 G.* (((G.inverse x0) G.* x0) G.* ((((G.inverse x0) G.* x4) G.* (G.inverse x4)) G.* ((x7 G.* x3) G.* ((G.inverse x3) G.* x8)))))) = ((x8 G.* (x0 G.* x7)) G.* x8) => equation.group

\lemma grequation968{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x3 G.* ((G.inverse x3) G.* x1)) = ((x1 G.* (x0 G.* ((G.inverse x0) G.* (x7 G.* x6)))) G.* ((G.inverse x6) G.* (((G.inverse x7) G.* (G.inverse x1)) G.* x1))) => equation.group

\lemma grequation969{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation970{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x9 G.* (G.inverse x9)) => equation.group

\lemma grequation971{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): ((x5 G.* x0) G.* (((G.inverse x0) G.* (G.inverse x5)) G.* (x2 G.* ((x4 G.* x4) G.* (G.inverse x4))))) = (x2 G.* x4) => equation.group

\lemma grequation972{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (((x8 G.* x0) G.* ((x2 G.* (G.inverse x2)) G.* (G.inverse x0))) G.* ((G.inverse x8) G.* (x10 G.* (G.inverse x10)))) => equation.group

\lemma grequation973{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x10 G.* x3) = (x10 G.* (x3 G.* (x8 G.* (G.inverse x8)))) => equation.group

\lemma grequation974{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): ((((x6 G.* x10) G.* (x3 G.* x8)) G.* (x5 G.* x2)) G.* ((x3 G.* (G.inverse x3)) G.* (((G.inverse x2) G.* (G.inverse x5)) G.* (G.inverse x8)))) = ((x6 G.* (((x9 G.* (G.inverse x9)) G.* x10) G.* (x4 G.* (G.inverse x4)))) G.* x3) => equation.group

\lemma grequation975{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 : G): (((x5 G.* x7) G.* (G.inverse x7)) G.* (x2 G.* ((G.inverse x2) G.* x2))) = (x5 G.* (((((x2 G.* x8) G.* (x7 G.* x4)) G.* (x2 G.* (G.inverse x2))) G.* (G.inverse x4)) G.* ((G.inverse x7) G.* (G.inverse x8)))) => equation.group

\lemma grequation976{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): (x6 G.* (G.inverse x6)) = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation977{G : Group}(x0 x1 x2 : G): (x1 G.* ((G.inverse x1) G.* x2)) = x2 => equation.group

\lemma grequation978{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = (x11 G.* (G.inverse x11)) => equation.group

\lemma grequation979{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 : G): G.ide = (x3 G.* (x6 G.* ((G.inverse x6) G.* (G.inverse x3)))) => equation.group

\lemma grequation980{G : Group}(x0 x1 x2 : G): (x2 G.* (G.inverse x2)) = (x0 G.* (G.inverse x0)) => equation.group

\lemma grequation981{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x0 = ((x8 G.* x6) G.* ((G.inverse x6) G.* ((G.inverse x8) G.* x0))) => equation.group

\lemma grequation982{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = ((((x14 G.* x11) G.* (x4 G.* ((x8 G.* (G.inverse x8)) G.* ((G.inverse x4) G.* ((G.inverse x11) G.* (G.inverse x14)))))) G.* x13) G.* (G.inverse x13)) => equation.group

\lemma grequation983{G : Group}(x0 x1 x2 x3 x4 : G): G.ide = (x4 G.* (x4 G.* ((G.inverse x4) G.* (G.inverse x4)))) => equation.group

\lemma grequation984{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = (((x3 G.* x12) G.* (G.inverse x12)) G.* (((x6 G.* x8) G.* (G.inverse x8)) G.* ((G.inverse x6) G.* (G.inverse x3)))) => equation.group

\lemma grequation985{G : Group}(x0 x1 x2 x3 x4 : G): x3 = x3 => equation.group

\lemma grequation986{G : Group}(x0 x1 : G): G.ide = (((x1 G.* (x0 G.* x0)) G.* (x0 G.* ((G.inverse x0) G.* (G.inverse x0)))) G.* ((G.inverse x0) G.* (G.inverse x1))) => equation.group

\lemma grequation987{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): (x4 G.* ((G.inverse x4) G.* x2)) = x2 => equation.group

\lemma grequation988{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : G): G.ide = ((((x6 G.* ((G.inverse x6) G.* x7)) G.* x8) G.* x4) G.* (((G.inverse x4) G.* (G.inverse x8)) G.* (G.inverse x7))) => equation.group

\lemma grequation989{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): ((((x14 G.* (G.inverse x14)) G.* ((x12 G.* x14) G.* (G.inverse x14))) G.* (x6 G.* (x7 G.* (G.inverse x7)))) G.* (x12 G.* x11)) = ((x12 G.* (x1 G.* (((G.inverse x1) G.* x6) G.* x12))) G.* x11) => equation.group

\lemma grequation990{G : Group}(x0 x1 x2 x3 x4 x5 x6 : G): x2 = (x5 G.* ((G.inverse x5) G.* x2)) => equation.group

\lemma grequation991{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): ((x6 G.* (G.inverse x6)) G.* x10) = ((x11 G.* ((G.inverse x11) G.* x11)) G.* (x8 G.* ((G.inverse x8) G.* ((G.inverse x11) G.* x10)))) => equation.group

\lemma grequation992{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 : G): x3 = x3 => equation.group

\lemma grequation993{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 : G): G.ide = ((x5 G.* x5) G.* ((G.inverse x5) G.* ((G.inverse x5) G.* (x7 G.* (G.inverse x7))))) => equation.group

\lemma grequation994{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): (x12 G.* ((G.inverse x12) G.* (x1 G.* (G.inverse x1)))) = (((x13 G.* x4) G.* (G.inverse x4)) G.* (G.inverse x13)) => equation.group

\lemma grequation995{G : Group}(x0 x1 x2 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation996{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 : G): G.ide = (((x4 G.* x5) G.* ((x0 G.* (G.inverse x0)) G.* ((G.inverse x5) G.* x2))) G.* (((G.inverse x2) G.* (G.inverse x4)) G.* (x6 G.* (G.inverse x6)))) => equation.group

\lemma grequation997{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 : G): G.ide = (x14 G.* (G.inverse x14)) => equation.group

\lemma grequation998{G : Group}(x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 : G): G.ide = (x1 G.* (G.inverse x1)) => equation.group

\lemma grequation999{G : Group}(x0 x1 : G): G.ide = ((x1 G.* (G.inverse x1)) G.* (x1 G.* (G.inverse x1))) => equation.group

